<?php

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_VERSION' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_VERSION', '0.1.2' );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_MIN_DIRECTORIST_VERSION_REQUIRMENT' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_MIN_DIRECTORIST_VERSION_REQUIRMENT', '7.2.2' );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_SCRIPT_VERSION' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_SCRIPT_VERSION', DIRECTORIST_WPML_INTEGRATION_VERSION );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_FILE' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_FILE', dirname( dirname( __FILE__ ) ) . '/directorist-wpml-integration.php' );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_BASE' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_BASE', dirname( dirname( __FILE__ ) ) . '/' );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_LANGUAGE_DIR' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_LANGUAGE_DIR', DIRECTORIST_WPML_INTEGRATION_BASE . 'languages' );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_POST_TYPE' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_POST_TYPE', 'directorist-wpml-integration' );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_TEMPLATE_PATH' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_TEMPLATE_PATH', DIRECTORIST_WPML_INTEGRATION_BASE . 'template/' );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_VIEW_PATH' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_VIEW_PATH', DIRECTORIST_WPML_INTEGRATION_BASE . 'view/' );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_URL' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_URL', plugin_dir_url( DIRECTORIST_WPML_INTEGRATION_FILE ) );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_ASSET_URL' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_ASSET_URL', DIRECTORIST_WPML_INTEGRATION_URL . 'assets/dist/' );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_JS_PATH' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_JS_PATH',  DIRECTORIST_WPML_INTEGRATION_ASSET_URL . 'js/' );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_CSS_PATH' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_CSS_PATH', DIRECTORIST_WPML_INTEGRATION_ASSET_URL . 'css/' );
}

if ( ! defined( 'DIRECTORIST_WPML_INTEGRATION_LOAD_MIN_FILES' ) ) {
    define( 'DIRECTORIST_WPML_INTEGRATION_LOAD_MIN_FILES', ! SCRIPT_DEBUG );
}