<div class="aptc_main_text">
<h2>Privacy Policy</h2>
<p class="last_update" style="font-style:italic; font-size:0.8em; color:gray; text-align:right; ">Last Updated date: <span class="shortcut">__LAST_UPDATE_TIME_AUTOMATIC__</span></p>
<div class="used_terms" style="font-style:italic; font-size:0.8em; color:gray;">
    <p>Used Terms:</p>
    <ul>
        <li><strong>__ORGANIZATION_NAME_AUTOMATIC__</strong> (also may referred as: "we", "us",  "Service", "our site", "our website", "this website", "__DOMAIN_NAME_AUTOMATIC__"...) More info about our organization can be found on “about us” page, if such exists)</li>
        <li>Personally identifying information (also referred as: "PII&rdquo;. It may include, but not limited to: Name, Email, Number, Address &hellip;)</li>
        <li>Terms Of Use (also may referred as: "Terms", "Terms and Conditions", "TOC";)</li>
    </ul>
</div>
<h3>Who we are</h3>
<p>You can learn more about our website through "about" page (available in navigation menu).</p>
<h3>Introduction</h3>
<p>This privacy policy will be applied fully and affect to your use of our website. By using our website, you consent to this Privacy Policy. This Privacy Policy applies to our site, only to information we collect through our site and does not apply to our collection of information from other sources. Here we explain what information may be collected on our website, what are our purposes, how we use this information and under what circumstances we may disclose the information to third parties. We will retain personal information as long as necessary for the fulfillment of those purposes. We collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date.</p>
<p>This <strong>Privacy Policy</strong>, together with the <strong>Terms and Conditions</strong> posted on our Website, set forth the general rules and policies governing your use of our Website. We make information about our policies and practices relating to the management of personal information readily available to customers.</p>
<h2>Website Visitors</h2>
<p>Like most website operators, we collect information of the sort that web browsers and servers typically make available, such as the browser type, language preference, Internet Protocol (IP) addresses, referring site, the date-time of visitor request and some other metrics. Our purpose in collecting such information is to better understand how our visitors use our website, to make the website more customized and optimized to visitor, to make security revisions of our systems and for similar important reasons. From time to time, we may release non-PII in the aggregate, e.g., by publishing a report on trends in the usage of its website.&nbsp;</p>
<p>We only disclose non-PII under the same circumstances that we disclose PII (as described below).</p>
<h2>Gathering of PII</h2>
<p>Your personal data is used to provide the information, goods and services, for billing, order fulfillment and other essential functions offered through our website to you. The amount and type of information our site gathers depends on the nature of the interaction. For example, when we permit some kind of functionality on our website (like: Registrations, comments, feedback forms or other common interactional functionalities) then visitor who tries to use such functionality, may be asked to provide a name, username, email address or similar common personal information.</p>
<h2>Security</h2>
<p>The security of your Personal Information is important to us, and we protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure or use, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure, as there exist 3<sup>rd</sup> party factors that are not under our control (internet provider, the server where our sites are hosted, the infrastructure or management system which serves our website and some other 3<sup>rd</sup> party factors). While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.</p>
<p>When you see that our website starts with HTTPS://, then it means our website uses secure sockets layers (SSL), which encrypts all information you input before it is sent to us.&nbsp;</p>
<h2>Links to External Sites</h2>
<p>Our Service may contain links to external sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. If you wish, you can review the Privacy Policy and Terms and Conditions of every site you visit.</p>
<p>We have no control over, and assume no responsibility for the content, privacy policies or practices of any third party sites, products or services.</p>
<h2>Advertisements</h2>
<p>If our website shows ads (like Google AdSense, DoubleClick or similar alternatives), then the ads appearing on our website may be delivered to users by advertising partners, who may set cookies. This information allows ad networks to (among other things) deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by our site and does not cover the use of cookies by any advertisers.</p>
<h2>Comments</h2>
<p>When visitors leave comments on the site we collect the data shown in the comments form, and also the visitor’s IP address and browser user agent string to help spam detection.An anonymized string created from your email address (also called a hash) may be provided to the Gravatar service to see if you are using it. The Gravatar service privacy policy is available here: https://automattic.com/privacy/. After approval of your comment, your profile picture is visible to the public in the context of your comment.</p>
<h2>Media</h2>
<p>If you upload images to the website, you should avoid uploading images with embedded location data (EXIF GPS) included. Visitors to the website can download and extract any location data from images on the website.</p>
<h2>Cookies</h2>
<p>To enrich and perfect your online experience, our site use "Cookies" (a cookie is only a string of information that a website stores on a visitor&rsquo;s device, and that the visitor&rsquo;s browser provides to the website each time the visitor returns), similar technologies and services provided by others to display personalized content, appropriate advertising or store your preferences on your computer.&nbsp; We use cookies to identify and track visitors, to distinguish one user from other users, their usage of our website, and their website access preferences. Cookies also provide us with information about how this website is used so we can keep it as up to date, relevant and error-free as possible. Visitors, who don&rsquo;t wish to have cookies placed on their computers, they should set their browser to refuse cookies before using our website, with the drawback that certain features of our website will not function properly without the aid of cookies.</p>
<p>By continuing to navigate our website without changing your cookie settings, you hereby acknowledge and agree to use cookies our cookies.</p>
<h2>How to view or delete your cookies?</h2>
<p>To delete cookies in your browser, please follow the instructions explained at <a href="https://aboutcookies.org/">https://aboutcookies.org/</a> .</p>
<h2>How can you request a copy or erasure of personal information about you?</h2>
<p>Contact us and send us the request for which of your personal information you want to be deleted.</p>
<p>&nbsp;</p>
<h2>How long we retain your data</h2>
<p>When you publish something, upload media, login, register or doing other actions on our site, the specific cookies might be saved in your browser in order to provide the stable functionality. Expiration dates of cookies varies, and we can't exactly describe the logic behind creation/deletion of the cookies (coming from our website) and how long each cookie might last or when it will be destroyed, as all these depends on dynamic nature of website CMS and user interaction with website. If you leave a comment, the comment and its metadata might be retained indefinitely. For users that register on our website (if any), we also store the personal information they provide in their user profile. All users can see, edit, or delete their personal information at any time (except they cannot change their username). Website administrators can also see and edit that information.</p>
<h2>Used services</h2>
<p>So, our site might use different third-party services, companies or individuals to facilitate our Service, to analyze, monitor, collect statistical information, change website design, provide embedded services, enrich user interface or add different kind of functionalities to our site. Such 3<sup>rd</sup> party services might use their specific cookies. Any data we collect will be used in accordance with our own privacy policy. Any data that a third-party service collects will be used in accordance with its privacy policy. We have a right to disclose statistical/usage/analytical information publicly for different purposes, like to describe our services to potential partners, provide it other reputable third parties or for other lawful purposes. Of course, this does not include your personally-identifying information, email addresses or other sensitive data. If you are concerned about your data, you have the right, subject to the payment of a small fee to request access to personal data which may hold or process about you. For better clarity, an example of the services our site might use, could be:</p>
<ul>
<li>Remarketing services to advertise on third party websites (including Google) to previous visitors to our site (for example, this could be in the form of an advertisement on the Google search results page, or other alternatives offered by third-party service). Third-party vendors, use cookies to serve ads based on someone&rsquo;s past visits (You can set preferences for how Google advertises to you using the Google Ad Preferences page).</li>
<li>Analytical services to monitor the behavior of visitors to our website. We may use third-party services (like Google Analytics or other alternatives) for such purposes.</li>
<li>Functional 3<sup>rd</sup> party services to enrich user interface, like JavaScript modules, messaging services, contact forms or other kind of plugins and which provide extra functionalities for our site.</li>
</ul>
<h2>Embedded content from other websites</h2>
<p>Pages on this site may include embedded content (e.g. videos, images, articles, etc.). Embedded content from other websites behaves in the exact same way as if the visitor has visited the other website.  These websites may collect data about you, use cookies, embed additional third-party tracking, and monitor your interaction with that embedded content, including tracking your interaction with the embedded content if you have an account and are logged in to that website.</p>
<p>Email newsletter</p>
<p>If our site has a newsletter, and you sign up to our newsletter, then we may use your email address to send you information about products or services. You can opt out of these at any point.</p>
<h2>Protection of Certain PII</h2>
<p>Our website discloses PII or Potentially PII only to those of its employees, contractors affiliated (partner) organizations or service providers (i) in order to process it on our organization&rsquo;s behalf or to provide services available at our website, and (ii) that have agreed not to disclose it to others. We will not rent, trade or sell PII or potentially PII to anyone. Other than to the recipients as described above, we disclose such information only:</p>
<ul>
<li>we are required by law, court order or other governmental request;</li>
<li>when we believe in good faith that disclosure is reasonably necessary to protect the property or ours, third parties or the public at large;</li>
<li>If we believe action is necessary for fraud, cyber crime or to protect the website, rights, personal safety of person(s);</li>
<li>To enforce or apply the terms of any of our user agreements;</li>
</ul>
<p>If you are a registered user on our site and have supplied your email address, we may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what&rsquo;s going on with us and our products. We expect to keep this type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. We take all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially PII or PII.</p>
<p>Children's Privacy</p>
<p>Our service does not address anyone under the age of 18 ("Children"). We do not knowingly collect personally identifiable information from children. If you are a parent or guardian and you are aware that your child has provided us with Personal Information, please contact us. When we discover that a child has provided us with Personal Information, we will delete such information from our storage.</p>
<h2>Affiliate Disclosure</h2>
<p>This site uses affiliate links and does earn a commission from certain links. This does not affect your purchases or the price you may pay.</p>
<h2>E-commerce</h2>
<p>In case if products or services are sold on our site, then those who engage in transactions with our website &ndash; by purchasing our services or products, are asked to provide additional information, including as necessary the personal and financial information required to process those transactions. In each case, our site collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor&rsquo;s interaction with our site. We do not disclose PII other than as described below. And visitors can always refuse to supply PII, with the caveat that it may prevent them from engaging in certain website-related activities. When making payments (unless there is any embedded payment processor fields built-in our website and you see that you make a payment directly within our website) you will be redirected to 3<sup>rd</sup> party payment processor&rsquo;s website (like PayPal, Visa, Stripe or other reputable payment processor website), where you put your credentials, and not on your site. SO, WE DO NOT HAVE AN ACCESS AND DON&rsquo;T COLLECT CREDIT CARD or PAYPAL CREDENTIALS.</p>
<h2>Business Transfers</h2>
<p>If our organization, website, or substantially all of its assets, were acquired, or in the unlikely event that we go out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of our website may continue to use your PII as set forth in this policy.</p>
<h2>What rights you have over your data</h2>
<p>If you have an account on this site, or have left comments, you can request to receive an exported file of the personal data we hold about you, including any data you have provided to us. You can also request that we erase any personal data we hold about you. This does not include any data we are obliged to keep for administrative, legal, or security purposes.</p>
<h2>&nbsp;</h2>
<h2>Changes in these policies</h2>
<p>Although most changes are likely to be minor, we may change these terms from time to time, and in our sole discretion. We will post those changes on this page, so we encourage visitors to frequently check this page for any changes. Your continued use of this site after any change in these terms will constitute your acceptance of such change.</p>
<h2>Contact Information</h2>
<p>If you have any questions about these terms, contact us via different methods listed on <b>"Contact Us"</b> page.</p>
</div>