<?php

if (!defined('ABSPATH')) exit;

class astound_chkagent extends astound_module {
	public function process($ip,&$stats=array(),&$options=array(),&$post=array()) {
		$badagents=array(
		"Abonti",
		"aggregator",
		"AhrefsBot",
		"asterias",
		"BDCbot",
		"BLEXBot",
		"BuiltBotTough",
		"Bullseye",
		"BunnySlippers",
		"ca-crawler",
		"CCBot",
		"Cegbfeieh",
		"CheeseBot",
		"CherryPicker",
		"CherryPickerElite",
		"CherryPickerSE",
		"CopyRightCheck",
		"cosmos",
		"Crescent Internet ToolPak",
		"Crescent",
		"discobot",
		"DittoSpyder",
		"DOC",
		"DotBot",
		"Download Ninja",
		"EasouSpider",
		"EmailCollector",
		"EmailSiphon",
		"EmailWolf",
		"EroCrawler",
		"Exabot",
		"ExtractorPro",
		"Fasterfox",
		"FeedBooster",
		"Foobot",
		"Genieo",
		"grub-client",
		"Harvest",
		"hloader",
		"httplib",
		"HTTrack",
		"humanlinks",
		"ieautodiscovery",
		"InfoNaviRobot",
		"IstellaBot",
		"Java/1.",
		"JennyBot",
		"k2spider",
		"Kenjin Spider",
		"Keyword Density/0.9",
		"larbin",
		"LexiBot",
		"libWeb",
		"libwww",
		"LinkextractorPro",
		"linko",
		"LinkScan/8.1a Unix",
		"LinkWalker",
		"LNSpiderguy",
		"lwp-trivial",
		"lwp-trivial",
		"magpie",
		"Mata Hari",
		'MaxPointCrawler',
		'MegaIndex',
		"Microsoft URL Control",
		"MIIxpc",
		"Mippin",
		"Missigua Locator",
		"Mister PiX",
		"MJ12bot",
		"moget",
		"MSIECrawler",
		"NetAnts",
		"NICErsPRO",
		"Niki-Bot",
		"NPBot",
		"Nutch",
		"Offline Explorer",
		"Openfind data gathere",
		"Openfind",
		'panscient.com',
		"PHP/5.{",
		"ProPowerBot/2.14",
		"ProWebWalker",
		"Python-urllib",
		"QueryN Metasearch",
		"RepoMonkey",
		"RepoMonkey",
		"RMA",
		'SemrushBot',
		"SeznamBot ",
		"SISTRIX",
		"sitecheck.Internetseer.com",
		"SiteSnagger",
		"SnapPreviewBot",
		"Sogou",
		"SpankBot",
		"spanner",
		"spbot",
		"Spinn3r",
		"suzuran",
		"Szukacz/1.4",
		"Teleport Pro/1.29",
		"Teleport",
		"TeleportPro",
		"Telesoft",
		"The Intraformant",
		"TheNomad",
		"TightTwatBot",
		"Titan",
		"toCrawl/UrlDispatcher",
		"True_Robot",
		"True_Robot/1.0",
		"turingos",
		"TurnitinBot",
		"UbiCrawler",
		"UnisterBot",
		"URLy Warning",
		"VCI WebViewer VCI WebViewer Win32",
		"VCI",
		"WBSearchBot",
		"Web Downloader/6.9",
		"Web Image Collector",
		"WebAuto",
		"WebBandit",
		"WebBandit/3.50",
		"WebCopier v4.0",
		"WebCopier",
		"WebEnhancer",
		"WebmasterWorldForumBot",
		"WebReaper",
		"WebSauger",
		"Website Quester",
		"Webster Pro",
		"WebStripper",
		"WebZip",
		"Wotbox",
		"wsr-agent",
		"WWW-Collector-E",
		"Xenu",
		"yandex",
		"Zao",
		"Zeus",
		"Zeus",
		"ZyBORG",
		'coccoc',
		'Incutio',
		'lmspider',
		'memoryBot',
		'SemrushBot',
		'serf',
		'Unknown',
		'uptime files'		
		);
		$agent="";
		if (array_key_exists('HTTP_USER_AGENT',$_SERVER)) $agent=$_SERVER['HTTP_USER_AGENT'];
		if (empty($agent)) {
			return 'Missing User Agent';
		}		
		// user agent can be spoofed. Move these exclusions to a better test when finished.
		if (stripos($agent,'docs.google.com/viewer')!==false) return false; // fix this?
		if (stripos($agent,'//www.google.com/bot.html)')!==false) return false; // fix this?
		if (stripos($agent,'bingbot)')!==false) return false; // fix this?
		foreach ($badagents as $a) {
			if (stripos($agent,$a)!==false) {
				return 'Deny List User agent:'.$a;
			}
		}
		return false;
	}
}
?>