<?php

namespace WPPayForm\App\Services;

class TransStrings
{
    public static function getStrings(): array
    {

        return [

            // ======================== Common ===========================

            'Unlock in Pro' => __('Unlock in Pro', 'wp-payment-form'),
            'Editor' => __('Editor', 'wp-payment-form'),
            'Email' => __('Email', 'wp-payment-form'),
            'Settings' => __('Settings', 'wp-payment-form'),
            'Entries' => __('Entries', 'wp-payment-form'),
            'Integrations' => __('Integrations', 'wp-payment-form'),


            // ======================== All Forms ========================

            'All Forms' => __('All Forms', 'wp-payment-form'),
            'Add New Form' => __('Add New Form', 'wp-payment-form'),
            'ID' => __('ID', 'wp-payment-form'),            
            'Title' => __('Title', 'wp-payment-form'),
            'Edit' => __('Edit', 'wp-payment-form'),
            'Preview' => __('Preview', 'wp-payment-form'),
            'Delete' => __('Delete', 'wp-payment-form'),
            'Duplicate Form' => __('Duplicate Form', 'wp-payment-form'),
            'Submissions' => __('Submissions', 'wp-payment-form'),
            'Create Date' => __('Create Date', 'wp-payment-form'),
            'ShortCode' => __('ShortCode', 'wp-payment-form'),
            'Search' => __('Search', 'wp-payment-form'),
            'Create a Form' => __('Create a Form', 'wp-payment-form'),
            'Select from demo' => __('Select from demo', 'wp-payment-form'),
            'Choose form' => __('Choose form', 'wp-payment-form'),
            'Choose form template' => __('Choose form template', 'wp-payment-form'),
            'Choose your new form template type!' => __('Choose your new form template type!', 'wp-payment-form'),
            'Advanced Editor' => __('Advanced Editor', 'wp-payment-form'),
            'Simple Form Templates' => __('Simple Form Templates', 'wp-payment-form'),
            'Customize only the ready input fields and enjoy simplest form building with the cleanest editor' => __('Customize only the ready input fields and enjoy simplest form building with the cleanest editor', 'wp-payment-form'),
            'Create blank form' => __('Create blank form', 'wp-payment-form'),
            'Experience ultimate form building with dynamic functionalities like conditional logic, CSS class, etc' => __('Experience ultimate form building with dynamic functionalities like conditional logic, CSS class, etc', 'wp-payment-form'),
            'Choose template' => __('Choose template', 'wp-payment-form'),
            'Category' => __('Category', 'wp-payment-form'),
            'All Category' => __('All Category', 'wp-payment-form'),
            'Search Form' => __('Search Form', 'wp-payment-form'),




            // ========================= Payment Summary ====================

            'Item' => __('Item', 'wp-payment-form'),
            'Qty' => __('Qty', 'wp-payment-form'),
            'Line Total' => __('Line Total', 'wp-payment-form'),
            'Price' => __('Price', 'wp-payment-form'),
            'Payment Summary' => __('Payment Summary', 'wp-payment-form'),


            // =========================== Customer ==========================

            'Customers' => __('Customers', 'wp-payment-form'),
            'Name' => __('Name', 'wp-payment-form'),
            'Customer From' => __('Customer From', 'wp-payment-form'),
            'Created At' => __('Created At', 'wp-payment-form'),


            // ========================== Entries ===========================

            'Form' => __('Form', 'wp-payment-form'),
            'Payment Status' => __('Payment Status', 'wp-payment-form'),
            'Payment Total' => __('Payment Total', 'wp-payment-form'),
            'Payment Method' => __('Payment Method', 'wp-payment-form'),
            'Entry Status' => __('Entry Status', 'wp-payment-form'),
            'Submitted At' => __('Submitted At', 'wp-payment-form'),
            'Actions' => __('Actions', 'wp-payment-form'),
            'Filter By Form' => __('Filter By Form', 'wp-payment-form'),
            'Filter By Payment Status' => __('Filter By Payment Status', 'wp-payment-form'),
            'Filter By Entry Status' => __('Filter By Entry Status', 'wp-payment-form'),

            
            // ========================== Paymattic Modules ===========================

            'Paymattic Modules' => __('Paymattic Modules', 'wp-payment-form'),
            'Here is the list of all Paymattic modules. You can enable or disable the modules based on your need.' => __('Here is the list of all Paymattic modules. You can enable or disable the modules based on your need.', 'wp-payment-form'),
            'Confirmation Settings' => __('Confirmation Settings', 'wp-payment-form'),
            'Form Confirmation Settings' => __('Form Confirmation Settings', 'wp-payment-form'),
            'Save Confirmation Settings' => __('Save Confirmation Settings', 'wp-payment-form'),
            'Receipt Customization' => __('Receipt Customization', 'wp-payment-form'),
            'reCaptcha Settings' => __('reCaptcha Settings', 'wp-payment-form'),
            'reCAPTCHA has not been configured yet! Please configure reCAPTCHA from Settings -> reCaptcha Settings' => __('reCAPTCHA has not been configured yet! Please configure reCAPTCHA from Settings -> reCaptcha Settings', 'wp-payment-form'),
            'Save reCAPTCHA Settings' => __('Save reCAPTCHA Settings', 'wp-payment-form'),
            'Turnstile Settings' => __('Turnstile Settings', 'wp-payment-form'),
            'Turnstile has not been configured yet! Please configure turnstile from Settings -> turnstile Settings' => __('Turnstile has not been configured yet! Please configure turnstile from Settings -> turnstile Settings', 'wp-payment-form'),
            'Save turnstile Settings' => __('Save turnstile Settings', 'wp-payment-form'),
            'Confirmation Type' => __('Confirmation Type', 'wp-payment-form'),
            'Message to show' => __('Message to show', 'wp-payment-form'),
            'After Form Submission' => __('After Form Submission', 'wp-payment-form'),
            'Receipt Header Content' => __('Receipt Header Content', 'wp-payment-form'),
            'Receipt Footer Content' => __('Receipt Footer Content', 'wp-payment-form'),
            'Save Receipt Settings' => __('Save Receipt Settings', 'wp-payment-form'),
            'Show Order Item details in the receipt (if any)' => __('Show Order Item details in the receipt (if any)', 'wp-payment-form'),
            'Show Submission info in the receipt' => __('Show Submission info in the receipt', 'wp-payment-form'),
            'This content will show wherever you use the shortcode:' => __('This content will show wherever you use the shortcode:', 'wp-payment-form'),
            'You may use this shortcode in email notification, success message or in your success page content' => __('You may use this shortcode in email notification, success message or in your success page content', 'wp-payment-form'),
            'Form Entries' => __('Form Entries', 'wp-payment-form'),
            'Export' => __('Export', 'wp-payment-form'),
            'Export as CSV' => __('Export as CSV', 'wp-payment-form'),
            'Export as Excel (xlsv)' => __('Export as Excel (xlsv)', 'wp-payment-form'),
            'Export as ODS' => __('Export as ODS', 'wp-payment-form'),
            'Add New Notification' => __('Add New Notification', 'wp-payment-form'),
            'Email Notifications' => __('Email Notifications', 'wp-payment-form'),
            'Status' => __('Status', 'wp-payment-form'),
            'Subject' => __('Subject', 'wp-payment-form'),
            'Sending Action' => __('Sending Action', 'wp-payment-form'),
            'All the seetings of this' => __('All the seetings of this', 'wp-payment-form'),
            'this email setup will be deleted.' => __('this email setup will be deleted.', 'wp-payment-form'),
            'Are you sure to delete this?' => __('Are you sure to delete this?', 'wp-payment-form'),
            'No email notifications configured yet.' => __('No email notifications configured yet.', 'wp-payment-form'),
            'Save' => __('Save', 'wp-payment-form'),
            'All Form Integrations' => __('All Form Integrations', 'wp-payment-form'),
            'Add New Integration' => __('Add New Integration', 'wp-payment-form'),
            'Integration' => __('Integration', 'wp-payment-form'),
            'Hide Form' => __('Hide Form', 'wp-payment-form'),
            'Reset Form' => __('Reset Form', 'wp-payment-form'),
            'Payment Settings' => __('Payment Settings', 'wp-payment-form'),
            'Saving' => __('Saving', 'wp-payment-form'),
            'Products' => __('Products', 'wp-payment-form'),
            'Donations' => __('Donations', 'wp-payment-form'),
            'Stripe Settings' => __('Stripe Settings', 'wp-payment-form'),
            'Push Form Data to Stripe' => __('Push Form Data to Stripe', 'wp-payment-form'),
            'Please Map meta Data for Stripe' => __('Please Map meta Data for Stripe', 'wp-payment-form'),
            'Stripe Meta Data' => __('Stripe Meta Data', 'wp-payment-form'),
            'Limit accepted methods' => __('Limit accepted methods ', 'wp-payment-form'),
            'Check all' => __('Check all', 'wp-payment-form'),
            'Stripe Account' => __('Stripe Account', 'wp-payment-form'),
            'As per global settings' => __('As per global settings', 'wp-payment-form'),
            'Custom Stripe Credentials' => __('Custom Stripe Credentials', 'wp-payment-form'),
            'PayPal Settings' => __('PayPal Settings', 'wp-payment-form'),
            'Custom PayPal ID' => __('Custom PayPal ID', 'wp-payment-form'),
            'Currency and Language Settings' => __('Currency and Language Settings', 'wp-payment-form'),
            'Save Currency Settings' => __('Save Currency Settings', 'wp-payment-form'),
            'Currency & Locale Setting' => __('Currency & Locale Setting', 'wp-payment-form'),
            'As Per Global Settings' => __('As Per Global Settings', 'wp-payment-form'),
            'Custom Settings' => __('Custom Settings', 'wp-payment-form'),
            'Form Design Settings' => __('Form Design Settings', 'wp-payment-form'),
            'Save Design Settings' => __('Save Design Settings', 'wp-payment-form'),
            'Form Layout' => __('Form Layout', 'wp-payment-form'),
            'Label Alignment' => __('Label Alignment', 'wp-payment-form'),
            'Asterisk Position' => __('Asterisk Position', 'wp-payment-form'),
            'Submit Button Position' => __('Submit Button Position', 'wp-payment-form'),
            'Form Element Stylings' => __('Form Element Stylings', 'wp-payment-form'),
            'Form Labels Font Weight' => __('Form Labels Font Weight', 'wp-payment-form'),
            'Make Labels as bold' => __('Make Labels as bold', 'wp-payment-form'),
            'Input Item Styles' => __('Input Item Styles', 'wp-payment-form'),
            'Enable Default form styles' => __('Enable Default form styles', 'wp-payment-form'),
            'Maximum Number of Entries' => __('Maximum Number of Entries', 'wp-payment-form'),
            'Form Scheduling' => __('Form Scheduling', 'wp-payment-form'),
            'Limit by payments' => __('Limit by payments', 'wp-payment-form'),
            'Login Requirement Settings' => __('Login Requirement Settings', 'wp-payment-form'),
            'Require user to be logged in' => __('Require user to be logged in', 'wp-payment-form'),
            'Form Scheduling & Restrictions' => __('Form Scheduling & Restrictions', 'wp-payment-form'),
            'Save Settings' => __('Save Settings', 'wp-payment-form'),
            'Custom CSS and JS' => __('Custom CSS and JS', 'wp-payment-form'),
            'Save CSS and JS' => __('Save CSS and JS', 'wp-payment-form'),
            'Custom CSS' => __('Custom CSS', 'wp-payment-form'),
            'You can write your custom CSS here for this form. This css will be applied in this current form only.' => __('You can write your custom CSS here for this form. This css will be applied in this current form only.', 'wp-payment-form'),
            'You may add' => __("You may add", 'wp-payment-form'),
            'as your css selector prefix to target this specific form' => __('as your css selector prefix to target this specific form', 'wp-payment-form'),
            "Please don't include" => __("Please don't include", 'wp-payment-form'),
            'Custom Javascript' => __('Custom Javascript', 'wp-payment-form'),
            'Your additional JS code will run after this form initialized. Please provide valid javascript code. Invalid JS code may break the Form.' => __('Your additional JS code will run after this form initialized. Please provide valid javascript code. Invalid JS code may break the Form.', 'wp-payment-form'),
            'The Following JavaScrip variables are available that you can use' => __('The Following JavaScrip variables are available that you can use', 'wp-payment-form'),
            'The Javascript DOM object of the Form' => __("The Javascript DOM object of the Form", 'wp-payment-form'),
            'Same Page' => __('Same Page', 'wp-payment-form'),
            'To a Page' => __('To a Page', 'wp-payment-form'),
            'To a Custom URL' => __('To a Custom URL', 'wp-payment-form'),
            'Add the following shortcode to the page to show payment receipt' => __('Add the following shortcode to the page to show payment receipt', 'wp-payment-form'),
            'Custom URL' => __('Custom URL', 'wp-payment-form'),
            "You don't have any form feed integration yet. Create new feed and connect your data to your favorite CRM/Marketing tool", "You don't have any form feed integration yet. Create new feed and connect your data to your favorite CRM/Marketing tool", 'wp-payment-form',



            // ================================= Payment ==============================

            'Payment Gateways' => __('Payment Gateways', 'wp-payment-form'),
            'PayPal Account' => __('PayPal Account', 'wp-payment-form'),
            'General Settings' => __('General Settings', 'wp-payment-form'),
            'Currency Settings' => __('Currency Settings', 'wp-payment-form'),
            'Stripe Checkout Locale' => __('Stripe Checkout Locale', 'wp-payment-form'),
            'Currency' => __('Currency', 'wp-payment-form'),
            'Currency Conversion Api Key' => __('Currency Conversion Api Key', 'wp-payment-form'),
            'Caching Interval' => __('Caching Interval', 'wp-payment-form'),
            'Currency Sign Position' => __('Currency Sign Position', 'wp-payment-form'),
            'Currency Separators' => __('Currency Separators', 'wp-payment-form'),
            'Comma as Thousand and Dot as Decimal (EG: 12,000.00)' => __('Comma as Thousand and Dot as Decimal (EG: 12,000.00)', 'wp-payment-form'),
            'Dot as Thousand and Comma as Decimal ( EG: 12.000,00 )' => __('Dot as Thousand and Comma as Decimal ( EG: 12.000,00 )', 'wp-payment-form'),
            'Hide decimal points for rounded numbers' => __('Hide decimal points for rounded numbers', 'wp-payment-form'),
            'Submission Abandoned After' => __('Submission Abandoned After', 'wp-payment-form'),
            'Donation Leaderboard Settings' => __('Donation Leaderboard Settings', 'wp-payment-form'),
            'Use this shortcode to configure donation leaderboard.' => __('Use this shortcode to configure donation leaderboard.', 'wp-payment-form'),
            'Read more' => __('Read more', 'wp-payment-form'),
            'Visibility Of Donation Leaderboard' => __('Visibility Of Donation Leaderboard', 'wp-payment-form'),
            'disable' => __('disable', 'wp-payment-form'),
            'For all form' => __('For all form', 'wp-payment-form'),
            'For specific form' => __('For specific form', 'wp-payment-form'),
            'Enable Honeypot Security' => __('Enable Honeypot Security', 'wp-payment-form'),
            'Enable your users to apply coupon/discount code while purchasing something using Paymattic Payment Module. Just activate this module and setup your your coupons.' => __('Enable your users to apply coupon/discount code while purchasing something using Paymattic Payment Module. Just activate this module and setup your your coupons.', 'wp-payment-form'),
            'Paymattic Coupon Module' => __('Paymattic Coupon Module', 'wp-payment-form'),
            'Enable Paymattic Coupon Module' => __('Enable Paymattic Coupon Module', 'wp-payment-form'),
            'reCAPTCHA Settings' => __('reCAPTCHA Settings', 'wp-payment-form'),
            'reCaptcha Mode' => __('reCaptcha Mode', 'wp-payment-form'),
            'Invisible' => __('Invisible', 'wp-payment-form'),
            'Disable' => __('Disable', 'wp-payment-form'),
            'Cloudflare Turnstile Settings' => __('Cloudflare Turnstile Settings', 'wp-payment-form'),
            'Clear Settings' => __('Clear Settings', 'wp-payment-form'),
            'Paymattic integrates with Cloudflare Turnstile, a free service that protects your website from spam and abuse. Please note, these settings are required only if you decide to use the Turnstile field.' => __('Paymattic integrates with Cloudflare Turnstile, a free service that protects your website from spam and abuse. Please note, these settings are required only if you decide to use the Turnstile field.', 'wp-payment-form'),
            'Please generate API key and API secret using Cloudflare Turnstile' => __('Please generate API key and API secret using Cloudflare Turnstile', 'wp-payment-form'),
            'Site Key' => __('Site Key', 'wp-payment-form'),
            'Secret Key' => __('Secret Key', 'wp-payment-form'),
            'Tools' => __('Tools', 'wp-payment-form'),
            'Export Form' => __('Export Form', 'wp-payment-form'),
            'Import Form' => __('Import Form', 'wp-payment-form'),
            'You can export any form as .json format that you have and then you can import the form in Paymattic' => __('You can export any form as .json format that you have and then you can import the form in Paymattic', 'wp-payment-form'),
            'Select the form to export' => __('Select the form to export', 'wp-payment-form'),
            'click here' => __('click here', 'wp-payment-form'),
            'You can import any form that is exported from paymattic' => __('You can import any form that is exported from paymattic', 'wp-payment-form'),
            'Upload .json file' => __('Upload .json file', 'wp-payment-form'),
            'If you already renewed your license then please' => __('If you already renewed your license then please', 'wp-payment-form'),
            'Paymattic Admin Permission' => __('Paymattic Admin Permission', 'wp-payment-form'),
            'Permission Settings' => __('Permission Settings','wp-payment-form'),
            'Check All' => __('Check All','wp-payment-form'),
            'Licensing' => __('Licensing', 'wp-payment-form'),
            'Click Here' => __('Click Here', 'wp-payment-form'),
            'Contact us' => __('Contact us', 'wp-payment-form'),
            'Your license is active! Enjoy Paymattic Pro' => __('Your license is active! Enjoy Paymattic Pro', 'wp-payment-form'),
            'Deactivate License' => __('Deactivate License', 'wp-payment-form'),
            'Activate WPPay Form Pro' => __('Activate WPPay Form Pro', 'wp-payment-form'),
            'Enter your license key' => __('Enter your license key', 'wp-payment-form'),
            'Activate Paymattic Pro' => __('Activate Paymattic Pro', 'wp-payment-form'),
            'Have a new license key? Please' => __('Have a new license key? Please', 'wp-payment-form'),
            'click here to check again' => __('click here to check again', 'wp-payment-form'),
            'Your License is Active' => __('Your License is Active', 'wp-payment-form'),
            'Licensing has been expired' => __('Licensing has been expired', 'wp-payment-form'),
            'Payment Analytics' => __('Payment Analytics', 'wp-payment-form'),
            'Total revenue' => __('Total revenue', 'wp-payment-form'),
            'New Customers' => __('New Customers', 'wp-payment-form'),
            'Total Customers' => __('Total Customers', 'wp-payment-form'),
            'Weekly Revenue' => __('Weekly Revenue', 'wp-payment-form'),
            'Top Customers' => __('Top Customers', 'wp-payment-form'),
            'Date' => __('Date', 'wp-payment-form'),
            'Net' => __('Net', 'wp-payment-form'),
            'Note' => __('Note', 'wp-payment-form'),
            'If you want use donation leaderboard then you have to use this shortcode' => __('If you want use donation leaderboard then you have to use this shortcode', 'wp-payment-form'),
            'in your page or post. for more customization follow this' => __('in your page or post. for more customization follow this', 'wp-payment-form'),
            'link' => __('link', 'wp-payment-form'),
            'Other Settings' => __('Other Settings', 'wp-payment-form'),
            'Disable IP Address Logging (If you check this then advanced analytics can not be performed)' => __("Disable IP Address Logging (If you check this then advanced analytics can not be performed)", 'wp-payment-form'),
            "You have to activate your Paymattic Pro by providing the license key bellow. If you don't have a license key please" => __("You have to activate your Paymattic Pro by providing the license key bellow. If you don't have a license key please", 'wp-payment-form'),
            'to get a license key from your purchase' => __('to get a license key from your purchase', 'wp-payment-form'),
            'Any questions or problems with your license' => __('Any questions or problems with your license', 'wp-payment-form'),
            'License Key' => __('License Key', 'wp-payment-form'),
            'Revenue breakdown' => __('Revenue breakdown', 'wp-payment-form'),
            'Select payment method' => __('Select payment method', 'wp-payment-form'),
            'Payment method settings' => __('Payment method settings', 'wp-payment-form'),
            'Default payment method' => __('Default payment method', 'wp-payment-form'),

        ];
    }
}