<?php

defined( 'ABSPATH' ) || exit;

return array(
	'name'                     => _x( '%s', 'post type general name', 'custom-post-types' ),
	'menu_name'                => __( '%s', 'custom-post-types' ),
	'singular_name'            => _x( '%s', 'post type singular name', 'custom-post-types' ),
	'add_new'                  => _x( 'Add New', 'post', 'custom-post-types' ),
	'add_new_item'             => __( 'Add New %s', 'custom-post-types' ),
	'edit_item'                => __( 'Edit %s', 'custom-post-types' ),
	'new_item'                 => __( 'New %s', 'custom-post-types' ),
	'view_item'                => __( 'View %s', 'custom-post-types' ),
	'view_items'               => __( 'View %s', 'custom-post-types' ),
	'search_items'             => __( 'Search %s', 'custom-post-types' ),
	'not_found'                => __( 'No %s found.', 'custom-post-types' ),
	'not_found_in_trash'       => __( 'No %s found in Trash.', 'custom-post-types' ),
	'parent_item_colon'        => __( 'Parent %s', 'custom-post-types' ),
	'all_items'                => __( 'All %s', 'custom-post-types' ),
	'archives'                 => __( '%s Archives', 'custom-post-types' ),
	'attributes'               => __( '%s Attributes', 'custom-post-types' ),
	'insert_into_item'         => __( 'Insert into %s', 'custom-post-types' ),
	'uploaded_to_this_item'    => __( 'Uploaded to this %s', 'custom-post-types' ),
	'featured_image'           => __( 'Featured image', 'custom-post-types' ),
	'set_featured_image'       => __( 'Set featured image', 'custom-post-types' ),
	'remove_featured_image'    => __( 'Remove featured image', 'custom-post-types' ),
	'use_featured_image'       => __( 'Use as featured image', 'custom-post-types' ),
	'filter_items_list'        => __( 'Filter %s list', 'custom-post-types' ),
	'items_list_navigation'    => __( '%s list navigation', 'custom-post-types' ),
	'items_list'               => __( '%s list', 'custom-post-types' ),
	'item_published'           => __( '%s published.', 'custom-post-types' ),
	'item_published_privately' => __( '%s published privately.', 'custom-post-types' ),
	'item_reverted_to_draft'   => __( '%s reverted to draft.', 'custom-post-types' ),
	'item_scheduled'           => __( '%s scheduled.', 'custom-post-types' ),
	'item_updated'             => __( '%s updated.', 'custom-post-types' ),
);
