CREATE TABLE IF NOT EXISTS `{WPDB_PREFIX}tblight_cars` (
    `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` varchar(255) NOT NULL,
    `alias` varchar(255) NOT NULL,
    `min_passenger_no` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
    `passenger_no` tinyint(3) UNSIGNED NOT NULL,
    `suitcase_no` tinyint(3) UNSIGNED NOT NULL,
    `child_seat_no` tinyint(3) UNSIGNED NOT NULL,
    `child_seat_price` decimal(10,2) NOT NULL DEFAULT 0.00,
    `price` decimal(10,2) NOT NULL,
    `minmil` decimal(5,2) NOT NULL,
    `minprice` decimal(10,2) NOT NULL,
    `unit_price_override` tinyint(1) NOT NULL DEFAULT 1,
    `unit_price` decimal(10,2) NOT NULL,
    `track_availability` tinyint(1) NOT NULL DEFAULT 1,
    `days_availability` text NOT NULL,
    `blocked_dates` text NOT NULL,
    `use_in_address` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Use as taxi in Address search',
    `charge_per_min` decimal(10,2) NOT NULL DEFAULT 0.00,
    `image` mediumtext NOT NULL,
    `text` text NOT NULL,
    `time_after_each_booking` float NOT NULL DEFAULT 0,
    `created` datetime NOT NULL,
    `created_by` int(10) UNSIGNED NOT NULL,
    `modified` datetime NOT NULL,
    `modified_by` int(10) UNSIGNED NOT NULL,
    `state` tinyint(4) NOT NULL,
    `ordering` int(11) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_state` (`state`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;