<?php

// Auto generated by wpfluent Installer.

return array(
    'name' => 'WPPayForm - Payments made simple',
    'slug' => 'wp-payment-form',
    'domain_path' => '/language',
    'text_domain' => 'wp-payment-form',
    'hook_prefix' => 'wppayform',
    'rest_namespace' => 'wppayform',
    'rest_version' => 'v2',
    'env' => 'dev',
);
