window.seraph_accel||(window.seraph_accel={});
(function(){seraph_accel.PluginAdmin={AdvertProductsContentInit:function(a,c,b,d,g,e){function f(h,t){var m="";if(Array.isArray(h)&&h.length){m+=seraph_accel.Ui.TagOpen("tr");for(var p=0;p<h.length;p++){var n=h[p];0<p&&0==p%g&&(m+=seraph_accel.Ui.TagClose("tr")+seraph_accel.Ui.TagOpen("tr"));var x=seraph_accel.Ui,C=x.Tag,y=seraph_accel.Ui,D=y.Tag,z=t,q="";var l=n.images;var u=z;if(Array.isArray(l)){for(var v=-1,A=2147483647,w=-1,B=2147483647,r=0;r<l.length;r++){var k=l[r];if(u==k.width){v=r;break}u<
k.width?(k=k.width-u,k<A&&(v=r,A=k)):(k=u-k.width,k<B&&(w=r,B=k))}l=-1!=v?l[v].url:-1!=w?l[w].url:null}else l=null;l&&(q+=seraph_accel.Ui.Tag("td",seraph_accel.Ui.Link(seraph_accel.Ui.Tag("img",null,{"class":"ctlSpaceAfter",width:z,src:l},!0),n.urlInfo,!0),{style:{width:"1px"}}));q+=seraph_accel.Ui.TagOpen("td");q+=seraph_accel.Ui.Tag("h3",n.title,{"class":"ctlSpaceVAfter",style:{"margin-top":0}});q+=seraph_accel.Ui.Tag("div",n.descr);n.urlInfo&&(q+=seraph_accel.Ui.Button(d,!0,null,"ctlSpaceVBefore",
"button",{onclick:"window.open( '"+n.urlInfo+"', '_blank' )"}));q+=seraph_accel.Ui.TagClose("td");n=seraph_accel.Ui.Tag("table",seraph_accel.Ui.Tag("tbody",seraph_accel.Ui.Tag("row",q)));m+=C.call(x,"td",D.call(y,"div",n,{style:{margin:"1em 1em 2em 1em"}}),{"class":"cx-lg-6 cx-xs-12",style:{"vertical-align":"top"}})}for(;p%g;p++)m+=seraph_accel.Ui.Tag("td",null,{"class":"cx-lg-6 cx-xs-12"});m+=seraph_accel.Ui.TagClose("tr");m=seraph_accel.Ui.Tag("table",seraph_accel.Ui.Tag("tbody",m))}jQuery(a).html(m)}
jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(c+"/v1/advert_products",{slug:"accelerator",locale:b}),type:"GET",dataType:"json"}).then(function(h){f(h,e)},function(h){f(null,0)})},SwitchTo:function(a,c,b){function d(f,h){g.hide();e.prop("disabled",!1);f&&window.open(b,"_blank").focus()}a=jQuery(".seraph_accel_switchto");var g=a.find(".seraph_accel_spinner"),e=a.find('input[type="button"]:not(.cancel)');g.show();e.prop("disabled",!0);jQuery.ajax({url:c,type:"post"}).then(function(f){d(!0)},function(f){d(!1,
"OK"===f.statusText?"PHP error: "+f.responseText:"Backend error: "+f.status+" "+f.statusText)})},RateItCont_Set:function(a,c,b){var d=jQuery("#"+a),g=d.find(".actions"),e=d.find(".seraph_accel_spinner");g.hide();e.show();jQuery.ajax({url:b+"="+(c?"rateItPostpone":"rateItDisable"),type:"post"}).then(function(f){d.hide()},function(f){g.show();e.hide()})},RateIt_Set:function(a,c){jQuery("#seraph_accel_RateIt_Message .actions").hide();jQuery("#seraph_accel_RateIt_Message .seraph_accel_spinner").show();
jQuery.ajax({url:c+"="+(a?"rateItPostpone":"rateItDisable"),type:"post"}).then(function(b){seraph_accel.Ui.BannerMsgClose(jQuery("#seraph_accel_RateIt_Message"))},function(b){jQuery("#seraph_accel_RateIt_Message .actions").show();jQuery("#seraph_accel_RateIt_Message .spinner").hide()})},ChangeVersion_Confirm:function(a){jQuery("#seraph_accel_ChangeVersion_Msg .actions").hide();jQuery("#seraph_accel_ChangeVersion_Msg .seraph_accel_spinner").show();jQuery.ajax({url:a+"=changeVersionConfirm",type:"post"}).then(function(c){seraph_accel.Ui.BannerMsgClose(jQuery("#seraph_accel_ChangeVersion_Msg"))},
function(c){jQuery("#seraph_accel_ChangeVersion_Msg .actions").show();jQuery("#seraph_accel_ChangeVersion_Msg .spinner").hide()})},SettImport:function(a,c,b,d){function g(){f.prop("disabled",!1);e.hide()}if(b){a=jQuery(a.parentNode);var e=a.find(".seraph_accel_spinner"),f=a.find("input.button");f.prop("disabled",!0);e.show();a=new FileReader;a.onabort=function(h){g()};a.onerror=function(h){g()};a.onload=function(h){jQuery.ajax({url:c+"=settImport&_wpnonce="+d+"&redir="+encodeURIComponent(location.href),
type:"post",contentType:"application/json",data:h.target.result}).then(function(t){t?location=t:location.reload()},function(t){g()})};a.readAsText(b)}},SettExport:function(a,c){function b(e){e&&window.saveAs(new Blob([e],{type:"text/json"}),"seraphinite-accelerator-settings.json");g.prop("disabled",!1);d.hide()}a=jQuery(a.parentNode);var d=a.find(".seraph_accel_spinner"),g=a.find("input.button");g.prop("disabled",!0);d.show();jQuery.ajax({url:c+"=settExport",type:"post"}).then(function(e){seraph_accel.Ui.ScriptLoad(document,
"https://cdn.jsdelivr.net/npm/file-saver@2.0.5/dist/FileSaver.min.js","file-saver").then(function(){b(e)},function(f){b()})},function(e){b()})},OnSettWizNext:function(a,c){var b=jQuery(a).closest("form");a=jQuery(a.parentNode);var d=b.find(".wizPages");b=d.find(">.active").first();b.get(0)?(c=c?b.next():b.prev(),c.get(0)&&(b.removeClass("active"),b=c)):b=d.children().first();b.addClass("active");c=!!b.next().get(0);b=!!b.prev().get(0);a.find("input.wizNext").prop("disabled",!c);a.find("input.wizPrev").prop("disabled",
!b);c?a.find("input.wizFinish").hide():a.find("input.wizFinish").show()}}})();
