<style>
    div.cmodsar-upgrade {
        display: inline-block;
        padding: 1em;
        background: #FFF;
        border: solid 1px #E0E0E0;
        max-width: 650px;
        margin: 1em 2em 1em 0;
    }
</style>

<div class="cmodsar-upgrade">
    <h3>Want more? Get the PRO</h3>
    <p>Professional version of <?php echo CMCR_NAME; ?> which gives the admin better tools to customize the Reports system:
        adding customization options, scheduling, e-mail templates, CSV export and a lot more reports. </p>
    <a href="<?php echo esc_attr(admin_url('admin.php?page=' . CMCR_PRO_OPTION)); ?>" class="button button-primary">Upgrade to PRO</a>
</div>