<?php wp_enqueue_style('font-awesome', plugin_dir_url(CART2CART_PLUGIN_ROOT_DIR . '/dir') . 'css/font-awesome.min.css'); ?>
<?php wp_enqueue_style('bootstrap', plugin_dir_url(CART2CART_PLUGIN_ROOT_DIR . '/dir') . 'css/bootstrap.min.css'); ?>
<?php wp_enqueue_style('module-core', plugin_dir_url(CART2CART_PLUGIN_ROOT_DIR . '/dir') . 'css/module-core.css'); ?>
<?php wp_enqueue_style('main-core', plugin_dir_url(CART2CART_PLUGIN_ROOT_DIR . '/dir') . 'css/main-core.css'); ?>
<?php wp_enqueue_style('redesign-main', plugin_dir_url(CART2CART_PLUGIN_ROOT_DIR . '/dir') . 'css/redesign-main.css'); ?>