<?php

namespace WPSocialReviews\App\Services\Includes;

class CountryNames
{
    public function get()
    {
        return array(
            '' => array(
                'label'    => 'Choose a language',
            ),
            'af' => array(
                'code'     => 'af',
                'value'    => 'af',
                'label'    => 'Afrikaans - af',
                'facebook' => 'af_ZA',
            ),
            'am' => array(
                'code'     => 'am',
                'value'    => 'am',
                'label'    => 'አማርኛ - am',
                'facebook' => 'am_ET',
            ),
            'ar' => array(
                'code'     => 'ar',
                'value'    => 'ar',
                'label'    => 'العربية - ar',
                'facebook' => 'ar_AR',
            ),
            'arg' => array(
                'code'     => 'an',
                'value'    => 'arg',
                'label'    => 'Aragonés - arg',
            ),
            'ary' => array(
                'code'     => 'ar',
                'value'    => 'ary',
                'label'    => 'العربية المغربية - ary',
                'facebook' => 'ar_AR',
            ),
            'as' => array(
                'code'     => 'as',
                'value'    => 'as',
                'label'    => 'অসমীয়া - as',
                'facebook' => 'as_IN',
            ),
            'az' => array(
                'code'     => 'az',
                'value'    => 'az',
                'label'    => 'Azərbaycan - az',
                'facebook' => 'az_AZ',
            ),
            'azb' => array(
                'code'     => 'az',
                'value'    => 'azb',
                'label'    => 'گؤنئی آذربایجان - azb',
            ),
            'bel' => array(
                'code'     => 'be',
                'value'    => 'bel',
                'label'    => 'Беларуская мова - bel',
                'facebook' => 'be_BY',
            ),
            'bg_BG' => array(
                'code'     => 'bg',
                'value'    => 'bg_BG',
                'label'    => 'български - bg_BG',
                'facebook' => 'bg_BG',
            ),
            'bn_BD' => array(
                'code'     => 'bn',
                'value'    => 'bn_BD',
                'label'    => 'বাংলা - bn_BD',
                'facebook' => 'bn_IN',
            ),
            'bo' => array(
                'code'     => 'bo',
                'value'    => 'bo',
                'label'    => 'བོད་ཡིག - bo',
            ),
            'bs_BA' => array(
                'code'     => 'bs',
                'value'    => 'bs_BA',
                'label'    => 'Bosanski - bs_BA',
                'facebook' => 'bs_BA',
            ),
            'ca' => array(
                'code'     => 'ca',
                'value'    => 'ca',
                'label'    => 'Català - ca',
                'facebook' => 'ca_ES',
            ),
            'ceb' => array(
                'code'     => 'ceb',
                'value'    => 'ceb',
                'label'    => 'Cebuano - ceb',
                'facebook' => 'cx_PH',
            ),
            'ckb' => array(
                'code'     => 'ku',
                'value'    => 'ckb',
                'label'    => 'کوردی - ckb',
                'facebook' => 'cb_IQ',
            ),
            'cs_CZ' => array(
                'code'     => 'cs',
                'value'    => 'cs_CZ',
                'label'    => 'Čeština - cs_CZ',
                'facebook' => 'cs_CZ',
            ),
            'cy' => array(
                'code'     => 'cy',
                'value'    => 'cy',
                'label'    => 'Cymraeg - cy',
                'facebook' => 'cy_GB',
            ),
            'da_DK' => array(
                'code'     => 'da',
                'value'    => 'da_DK',
                'label'    => 'Dansk - da_DK',
                'facebook' => 'da_DK',
            ),
            'de_AT' => array(
                'code'     => 'de',
                'value'    => 'de_AT',
                'label'    => 'Deutsch - de_AT',
                'facebook' => 'de_DE',
            ),
            'de_CH' => array(
                'code'     => 'de',
                'value'    => 'de_CH',
                'label'    => 'Deutsch - de_CH',
                'facebook' => 'de_DE',
            ),
            'de_CH_informal' => array(
                'code'     => 'de',
                'value'    => 'de_CH_informal',
                'label'    => 'Deutsch - de_CH_informal',
                'facebook' => 'de_DE',
            ),
            'de_DE' => array(
                'code'     => 'de',
                'value'    => 'de_DE',
                'label'    => 'Deutsch - de_DE',
                'facebook' => 'de_DE',
            ),
            'de_DE_formal' => array(
                'code'     => 'de',
                'value'    => 'de_DE_formal',
                'label'    => 'Deutsch - de_DE_formal',
                'facebook' => 'de_DE',
            ),
            'dsb' => array(
                'code'     => 'dsb',
                'value'    => 'dsb',
                'label'    => 'Dolnoserbšćina - dsb',
            ),
            'dzo' => array(
                'code'     => 'dz',
                'value'    => 'dzo',
                'label'    => 'རྫོང་ཁ - dzo',
            ),
            'el' => array(
                'code'     => 'el',
                'value'    => 'el',
                'label'    => 'Ελληνικά - el',
                'facebook' => 'el_GR',
            ),
            'en_AU' => array(
                'code'     => 'en',
                'value'    => 'en_AU',
                'label'    => 'English - en_AU',
                'facebook' => 'en_US',
            ),
            'en_CA' => array(
                'code'     => 'en',
                'value'    => 'en_CA',
                'label'    => 'English - en_CA',
                'facebook' => 'en_US',
            ),
            'en_GB' => array(
                'code'     => 'en',
                'value'    => 'en_GB',
                'label'    => 'English - en_GB',
                'facebook' => 'en_GB',
            ),
            'en_NZ' => array(
                'code'     => 'en',
                'value'    => 'en_NZ',
                'label'    => 'English - en_NZ',
                'facebook' => 'en_US',
            ),
            'en_US' => array(
                'code'     => 'en',
                'value'    => 'en_US',
                'label'    => 'English - en_US',
                'facebook' => 'en_US',
            ),
            'en_ZA' => array(
                'code'     => 'en',
                'value'    => 'en_ZA',
                'label'    => 'English - en_ZA',
                'facebook' => 'en_US',
            ),
            'eo' => array(
                'code'     => 'eo',
                'value'    => 'eo',
                'label'    => 'Esperanto - eo',
                'facebook' => 'eo_EO',
            ),
            'es_AR' => array(
                'code'     => 'es',
                'value'    => 'es_AR',
                'label'    => 'Español - es_AR',
                'facebook' => 'es_LA',
            ),
            'es_CL' => array(
                'code'     => 'es',
                'value'    => 'es_CL',
                'label'    => 'Español - es_CL',
                'facebook' => 'es_CL',
            ),
            'es_CO' => array(
                'code'     => 'es',
                'value'    => 'es_CO',
                'label'    => 'Español - es_CO',
                'facebook' => 'es_CO',
            ),
            'es_CR' => array(
                'code'     => 'es',
                'value'    => 'es_CR',
                'label'    => 'Español - es_CR',
                'facebook' => 'es_LA',
            ),
            'es_DO' => array(
                'code'     => 'es',
                'value'    => 'es_DO',
                'label'    => 'Español - es_DO',
                'facebook' => 'es_LA',
            ),
            'es_EC' => array(
                'code'     => 'es',
                'value'    => 'es_EC',
                'label'    => 'Español - es_EC',
                'facebook' => 'es_LA',
            ),
            'es_ES' => array(
                'code'     => 'es',
                'value'    => 'es_ES',
                'label'    => 'Español - es_ES',
                'facebook' => 'es_ES',
            ),
            'es_GT' => array(
                'code'     => 'es',
                'value'    => 'es_GT',
                'label'    => 'Español - es_GT',
                'facebook' => 'es_LA',
            ),
            'es_MX' => array(
                'code'     => 'es',
                'value'    => 'es_MX',
                'label'    => 'Español - es_MX',
                'facebook' => 'es_MX',
            ),
            'es_PE' => array(
                'code'     => 'es',
                'value'    => 'es_PE',
                'label'    => 'Español - es_PE',
                'facebook' => 'es_LA',
            ),
            'es_PR' => array(
                'code'     => 'es',
                'value'    => 'es_PR',
                'label'    => 'Español - es_PR',
                'facebook' => 'es_LA',
            ),
            'es_UY' => array(
                'code'     => 'es',
                'value'    => 'es_UY',
                'label'    => 'Español - es_UY',
                'facebook' => 'es_LA',
            ),
            'es_VE' => array(
                'code'     => 'es',
                'value'    => 'es_VE',
                'label'    => 'Español - es_VE',
                'facebook' => 'es_VE',
            ),
            'et' => array(
                'code'     => 'et',
                'value'    => 'et',
                'label'    => 'Eesti - et',
                'facebook' => 'et_EE',
            ),
            'eu' => array(
                'code'     => 'eu',
                'value'    => 'eu',
                'label'    => 'Euskara - eu',
                'facebook' => 'eu_ES',
            ),
            'fa_AF' => array(
                'code'     => 'fa',
                'value'    => 'fa_AF',
                'label'    => 'فارسی - fa_AF',
                'facebook' => 'fa_IR',
            ),
            'fa_IR' => array(
                'code'     => 'fa',
                'value'    => 'fa_IR',
                'label'    => 'فارسی - fa_IR',
                'facebook' => 'fa_IR',
            ),
            'fi' => array(
                'code'     => 'fi',
                'value'    => 'fi',
                'label'    => 'Suomi - fi',
                'facebook' => 'fi_FI',
            ),
            'fo' => array(
                'code'     => 'fo',
                'value'    => 'fo',
                'label'    => 'Føroyskt - fo',
                'facebook' => 'fo_FO',
            ),
            'fr_BE' => array(
                'code'     => 'fr',
                'value'    => 'fr_BE',
                'label'    => 'Français - fr_BE',
                'facebook' => 'fr_FR',
            ),
            'fr_CA' => array(
                'code'     => 'fr',
                'value'    => 'fr_CA',
                'label'    => 'Français - fr_CA',
                'facebook' => 'fr_CA',
            ),
            'fr_FR' => array(
                'code'     => 'fr',
                'value'    => 'fr_FR',
                'label'    => 'Français - fr_FR',
                'facebook' => 'fr_FR',
            ),
            'fur' => array(
                'code'     => 'fur',
                'value'    => 'fur',
                'label'    => 'Furlan - fur',
            ),
            'fy' => array(
                'code'     => 'fy',
                'value'    => 'fy',
                'label'    => 'Frysk - fy',
                'facebook' => 'fy_NL',
            ),
            'gd' => array(
                'code'     => 'gd',
                'value'    => 'gd',
                'label'    => 'Gàidhlig - gd',
            ),
            'gl_ES' => array(
                'code'     => 'gl',
                'value'    => 'gl_ES',
                'label'    => 'Galego - gl_ES',
                'facebook' => 'gl_ES',
            ),
            'gu' => array(
                'code'     => 'gu',
                'value'    => 'gu',
                'label'    => 'ગુજરાતી - gu',
                'facebook' => 'gu_IN',
            ),
            'haz' => array(
                'code'     => 'haz',
                'value'    => 'haz',
                'label'    => 'هزاره گی - haz',
            ),
            'he_IL' => array(
                'code'     => 'he',
                'value'    => 'he_IL',
                'label'    => 'עברית - he_IL',
                'facebook' => 'he_IL',
            ),
            'hi_IN' => array(
                'code'     => 'hi',
                'value'    => 'hi_IN',
                'label'    => 'हिन्दी - hi_IN',
                'facebook' => 'hi_IN',
            ),
            'hr' => array(
                'code'     => 'hr',
                'value'    => 'hr',
                'label'    => 'Hrvatski - hr',
                'facebook' => 'hr_HR',
            ),
            'hu_HU' => array(
                'code'     => 'hu',
                'value'    => 'hu_HU',
                'label'    => 'Magyar - hu_HU',
                'facebook' => 'hu_HU',
            ),
            'hsb' => array(
                'code'     => 'hsb',
                'value'    => 'hsb',
                'label'    => 'Hornjoserbšćina - hsb',
            ),
            'hy' => array(
                'code'     => 'hy',
                'value'    => 'hy',
                'label'    => 'Հայերեն - hy',
                'facebook' => 'hy_AM',
            ),
            'id_ID' => array(
                'code'     => 'id',
                'value'    => 'id_ID',
                'label'    => 'Bahasa Indonesia - id_ID',
                'facebook' => 'id_ID',
            ),
            'is_IS' => array(
                'code'     => 'is',
                'value'    => 'is_IS',
                'label'    => 'Íslenska - is_IS',
                'facebook' => 'is_IS',
            ),
            'it_IT' => array(
                'code'     => 'it',
                'value'    => 'it_IT',
                'label'    => 'Italiano - it_IT',
                'facebook' => 'it_IT',
            ),
            'ja' => array(
                'code'     => 'ja',
                'value'    => 'ja',
                'label'    => '日本語 - ja',
                'facebook' => 'ja_JP',
            ),
            'jv_ID' => array(
                'code'     => 'jv',
                'value'    => 'jv_ID',
                'label'    => 'Basa Jawa - jv_ID',
                'facebook' => 'jv_ID',
            ),
            'ka_GE' => array(
                'code'     => 'ka',
                'value'    => 'ka_GE',
                'label'    => 'ქართული - ka_GE',
                'facebook' => 'ka_GE',
            ),
            'kab' => array(
                'code'     => 'kab',
                'value'    => 'kab',
                'label'    => 'Taqbaylit - kab',
            ),
            'kir' => array(
                'code'     => 'ky',
                'value'    => 'kir',
                'label'    => 'Кыргызча - kir',
            ),
            'kk' => array(
                'code'     => 'kk',
                'value'    => 'kk',
                'label'    => 'Қазақ тілі - kk',
                'facebook' => 'kk_KZ',
            ),
            'km' => array(
                'code'     => 'km',
                'value'    => 'km',
                'label'    => 'ភាសាខ្មែរ - km',
                'facebook' => 'km_KH',
            ),
            'kn' => array(
                'code'     => 'kn',
                'value'    => 'kn',
                'label'    => 'ಕನ್ನಡ - kn',
                'facebook' => 'kn_IN',
            ),
            'ko_KR' => array(
                'code'     => 'ko',
                'value'    => 'ko_KR',
                'label'    => '한국어 - ko_KR',
                'facebook' => 'ko_KR',
            ),
            'lo' => array(
                'code'     => 'lo',
                'value'    => 'lo',
                'label'    => 'ພາສາລາວ - lo',
                'facebook' => 'lo_LA',
            ),
            'lt_LT' => array(
                'code'     => 'lt',
                'value'    => 'lt_LT',
                'label'    => 'Lietuviškai - lt_LT',
                'facebook' => 'lt_LT',
            ),
            'lv' => array(
                'code'     => 'lv',
                'value'    => 'lv',
                'label'    => 'Latviešu valoda - lv',
                'facebook' => 'lv_LV',
            ),
            'mk_MK' => array(
                'code'     => 'mk',
                'value'    => 'mk_MK',
                'label'    => 'македонски јазик - mk_MK',
                'facebook' => 'mk_MK',
            ),
            'ml_IN' => array(
                'code'     => 'ml',
                'value'    => 'ml_IN',
                'label'    => 'മലയാളം - ml_IN',
                'facebook' => 'ml_IN',
            ),
            'mn' => array(
                'code'     => 'mn',
                'value'    => 'mn',
                'label'    => 'Монгол хэл - mn',
                'facebook' => 'mn_MN',
            ),
            'mr' => array(
                'code'     => 'mr',
                'value'    => 'mr',
                'label'    => 'मराठी - mr',
                'facebook' => 'mr_IN',
            ),
            'ms_MY' => array(
                'code'     => 'ms',
                'value'    => 'ms_MY',
                'label'    => 'Bahasa Melayu - ms_MY',
                'facebook' => 'ms_MY',
            ),
            'my_MM' => array(
                'code'     => 'my',
                'value'    => 'my_MM',
                'label'    => 'ဗမာစာ - my_MM',
                'facebook' => 'my_MM',
            ),
            'nb_NO' => array(
                'code'     => 'nb',
                'value'    => 'nb_NO',
                'label'    => 'Norsk Bokmål - nb_NO',
                'facebook' => 'nb_NO',
            ),
            'ne_NP' => array(
                'code'     => 'ne',
                'value'    => 'ne_NP',
                'label'    => 'नेपाली - ne_NP',
                'facebook' => 'ne_NP',
            ),
            'nl_BE' => array(
                'code'     => 'nl',
                'value'    => 'nl_BE',
                'label'    => 'Nederlands - nl_BE',
                'facebook' => 'nl_BE',
            ),
            'nl_NL' => array(
                'code'     => 'nl',
                'value'    => 'nl_NL',
                'label'    => 'Nederlands - nl_NL',
                'facebook' => 'nl_NL',
            ),
            'nl_NL_formal' => array(
                'code'     => 'nl',
                'value'    => 'nl_NL_formal',
                'label'    => 'Nederlands - nl_NL_formal',
                'facebook' => 'nl_NL',
            ),
            'nn_NO' => array(
                'code'     => 'nn',
                'value'    => 'nn_NO',
                'label'    => 'Norsk Nynorsk - nn_NO',
                'facebook' => 'nn_NO',
            ),
            'oci' => array(
                'code'     => 'oc',
                'value'    => 'oci',
                'label'    => 'Occitan - oci',
            ),
            'pa_IN' => array(
                'code'     => 'pa',
                'value'    => 'pa_IN',
                'label'    => 'ਪੰਜਾਬੀ - pa_IN',
                'facebook' => 'pa_IN',
            ),
            'pl_PL' => array(
                'code'     => 'pl',
                'value'    => 'pl_PL',
                'label'    => 'Polski - pl_PL',
                'facebook' => 'pl_PL',
            ),
            'ps' => array(
                'code'     => 'ps',
                'value'    => 'ps',
                'label'    => 'پښتو - ps',
                'facebook' => 'ps_AF',
            ),
            'pt_AO' => array(
                'code'     => 'pt',
                'value'    => 'pt_AO',
                'label'    => 'Português - pt_AO',
                'facebook' => 'pt_PT',
            ),
            'pt_BR' => array(
                'code'     => 'pt',
                'value'    => 'pt_BR',
                'label'    => 'Português - pt_BR',
                'facebook' => 'pt_BR',
            ),
            'pt_PT' => array(
                'code'     => 'pt',
                'value'    => 'pt_PT',
                'label'    => 'Português - pt_PT',
                'facebook' => 'pt_PT',
            ),
            'pt_PT_ao90' => array(
                'code'     => 'pt',
                'value'    => 'pt_PT_ao90',
                'label'    => 'Português - pt_PT_ao90',
                'facebook' => 'pt_PT',
            ),
            'rhg' => array(
                'code'     => 'rhg',
                'value'    => 'rhg',
                'label'    => 'Ruáinga - rhg',
            ),
            'ro_RO' => array(
                'code'     => 'ro',
                'value'    => 'ro_RO',
                'label'    => 'Română - ro_RO',
                'facebook' => 'ro_RO',
            ),
            'ru_RU' => array(
                'code'     => 'ru',
                'value'    => 'ru_RU',
                'label'    => 'Русский - ru_RU',
                'facebook' => 'ru_RU',
            ),
            'sah' => array(
                'code'     => 'sah',
                'value'    => 'sah',
                'label'    => 'Сахалыы - sah',
            ),
            'si_LK' => array(
                'code'     => 'si',
                'value'    => 'si_LK',
                'label'    => 'සිංහල - si_LK',
                'facebook' => 'si_LK',
            ),
            'sk_SK' => array(
                'code'     => 'sk',
                'value'    => 'sk_SK',
                'label'    => 'Slovenčina - sk_SK',
                'facebook' => 'sk_SK',
            ),
            'skr' => array(
                'code'     => 'skr',
                'value'    => 'skr',
                'label'    => 'سرائیکی - skr',
            ),
            'sl_SI' => array(
                'code'     => 'sl',
                'value'    => 'sl_SI',
                'label'    => 'Slovenščina - sl_SI',
                'facebook' => 'sl_SI',
            ),
            'snd' => array(
                'code'     => 'sd',
                'value'    => 'snd',
                'label'    => 'سنڌي - snd',
            ),
            'so_SO' => array(
                'code'     => 'so',
                'value'    => 'so_SO',
                'label'    => 'Af-Soomaali - so_SO',
                'facebook' => 'so_SO',
            ),
            'sq' => array(
                'code'     => 'sq',
                'value'    => 'sq',
                'label'    => 'Shqip - sq',
                'facebook' => 'sq_AL',
            ),
            'sr_RS' => array(
                'code'     => 'sr',
                'value'    => 'sr_RS',
                'label'    => 'Српски језик - sr_RS',
                'facebook' => 'sr_RS',
            ),
            'su_ID' => array(
                'code'     => 'su',
                'value'    => 'su_ID',
                'label'    => 'Basa Sunda - su_ID',
                'facebook' => 'su_ID',
            ),
            'sv_SE' => array(
                'code'     => 'sv',
                'value'    => 'sv_SE',
                'label'    => 'Svenska - sv_SE',
                'facebook' => 'sv_SE',
            ),
            'sw' => array(
                'code'     => 'sw',
                'value'    => 'sw',
                'label'    => 'Kiswahili - sw',
                'facebook' => 'sw_KE',
            ),
            'szl' => array(
                'code'     => 'szl',
                'value'    => 'szl',
                'label'    => 'Ślōnskŏ gŏdka - szl',
                'facebook' => 'sz_PL',
            ),
            'ta_IN' => array(
                'code'     => 'ta',
                'value'    => 'ta_IN',
                'label'    => 'தமிழ் - ta_IN',
                'facebook' => 'ta_IN',
            ),
            'ta_LK' => array(
                'code'     => 'ta',
                'value'    => 'ta_LK',
                'label'    => 'தமிழ் - ta_LK',
                'facebook' => 'ta_IN',
            ),
            'tah' => array(
                'code'     => 'ty',
                'value'    => 'tah',
                'label'    => 'Reo Tahiti - tah',
            ),
            'te' => array(
                'code'     => 'te',
                'value'    => 'te',
                'label'    => 'తెలుగు - te',
                'facebook' => 'te_IN',
            ),
            'th' => array(
                'code'     => 'th',
                'value'    => 'th',
                'label'    => 'ไทย - th',
                'facebook' => 'th_TH',
            ),
            'tl' => array(
                'code'     => 'tl',
                'value'    => 'tl',
                'label'    => 'Tagalog - tl',
                'facebook' => 'tl_PH',
            ),
            'tr_TR' => array(
                'code'     => 'tr',
                'value'    => 'tr_TR',
                'label'    => 'Türkçe - tr_TR',
                'facebook' => 'tr_TR',
            ),
            'tt_RU' => array(
                'code'     => 'tt',
                'value'    => 'tt_RU',
                'label'    => 'Татар теле - tt_RU',
                'facebook' => 'tt_RU',
            ),
            'ug_CN' => array(
                'code'     => 'ug',
                'value'    => 'ug_CN',
                'label'    => 'Uyƣurqə - ug_CN',
            ),
            'uk' => array(
                'code'     => 'uk',
                'value'    => 'uk',
                'label'    => 'Українська - uk',
                'facebook' => 'uk_UA',
            ),
            'ur' => array(
                'code'     => 'ur',
                'value'    => 'ur',
                'label'    => 'اردو - ur',
                'facebook' => 'ur_PK',
            ),
            'uz_UZ' => array(
                'code'     => 'uz',
                'value'    => 'uz_UZ',
                'label'    => 'Oʻzbek - uz_UZ',
                'facebook' => 'uz_UZ',
            ),
            'vec' => array(
                'code'     => 'vec',
                'value'    => 'vec',
                'label'    => 'Vèneto - vec',
            ),
            'vi' => array(
                'code'     => 'vi',
                'value'    => 'vi',
                'label'    => 'Tiếng Việt - vi',
                'facebook' => 'vi_VN',
            ),
            'zh_CN' => array(
                'code'     => 'zh',
                'value'    => 'zh_CN',
                'label'    => '中文 (中国) - zh_CN',
                'facebook' => 'zh_CN',
            ),
            'zh_HK' => array(
                'code'     => 'zh',
                'value'    => 'zh_HK',
                'label'    => '中文 (香港) - zh_HK',
                'facebook' => 'zh_HK',
            ),
            'zh_TW' => array(
                'code'     => 'zh',
                'value'    => 'zh_TW',
                'label'    => '中文 (台灣) - zh_TW',
                'facebook' => 'zh_TW',
            ),
        );
    }
}