<?php
/**
 * This is the gettext list of abbreviations from the various weather providers
 *
 * @package wp-forecast
 */

/**
 * Defines gettext array of necessary translations for each weather provider
 */
function xgettext_dummy() {
	 __( 'loc' );
	__( '01' );
	__( '02' );
	__( '03' );
	__( '04' );
	__( '05' );
	__( '06' );
	__( '07' );
	__( '08' );
	__( '11' );
	__( '12' );
	__( '13' );
	__( '14' );
	__( '15' );
	__( '16' );
	__( '17' );
	__( '18' );
	__( '19' );
	__( '20' );
	__( '21' );
	__( '22' );
	__( '23' );
	__( '24' );
	__( '25' );
	__( '26' );
	__( '29' );
	__( '30' );
	__( '31' );
	__( '32' );
	__( '33' );
	__( '34' );
	__( '35' );
	__( '36' );
	__( '37' );
	__( '38' );
	__( '39' );
	__( '40' );
	__( '41' );
	__( '42' );
	__( '43' );
	__( '44' );
	__( 'Monday' );
	__( 'Tuesday' );
	__( 'Wednesday' );
	__( 'Thursday' );
	__( 'Friday' );
	__( 'Saturday' );
	__( 'Sunday' );
	__( 'N' );
	__( 'E' );
	__( 'W' );
	__( 'S' );
	__( '30% Chance Drizzle' );
	__( '30% Chance Freezing Drizzle' );
	__( '30% Chance Freezing Rain' );
	__( '30% Chance Frozen Drizzle' );
	__( '30% Chance Frozen Mix' );
	__( '30% Chance Rain Shower' );
	__( '30% Chance Snow Shower' );
	__( '30% Chance of Drizzle' );
	__( '30% Chance of Flurry' );
	__( '30% Chance of Flurry' );
	__( '30% Chance of Frozen Mix' );
	__( '30% Chance of Light Snow' );
	__( '30% Chance of Rain' );
	__( '30% Chance of Sleet' );
	__( '30% Chance of Snow' );
	__( '30% Chance of Storms' );
	__( '40% Chance Drizzle' );
	__( '40% Chance Fozen Drizzle' );
	__( '40% Chance Freezing Drizzle' );
	__( '40% Chance Freezing Rain' );
	__( '40% Chance Frozen Drizzle' );
	__( '40% Chance Frozen Mix' );
	__( '40% Chance Rain Shower' );
	__( '40% Chance Snow Shower' );
	__( '40% Chance of Drizzle' );
	__( '40% Chance of Flurry' );
	__( '40% Chance of Frozen Mix' );
	__( '40% Chance of Light Snow' );
	__( '40% Chance of Rain' );
	__( '40% Chance of Sleet' );
	__( '40% Chance of Snow' );
	__( '40% Chance of Storms' );
	__( '50% Chance Freezing Drizzle' );
	__( '50% Chance Freezing Rain' );
	__( '50% Chance Rain Shower' );
	__( '50% Chance Snow Shower' );
	__( '50% Chance of Drizzle' );
	__( '50% Chance of Flurry' );
	__( '50% Chance of Frozen Mix' );
	__( '50% Chance of Light Snow' );
	__( '50% Chance of Rain' );
	__( '50% Chance of Sleet' );
	__( '50% Chance of Snow' );
	__( '50% Chance of Storms' );
	__( 'Chance Freezing Drizzle' );
	__( 'Chance Freezing Rain' );
	__( 'Chance Rain Shower' );
	__( 'Chance Snow Shower' );
	__( 'Chance of Drizzle' );
	__( 'Chance of Flurry' );
	__( 'Chance of Freezing Drizzle' );
	__( 'Chance of Frozen Drizzle' );
	__( 'Chance of Frozen Mix' );
	__( 'Chance of Light Snow' );
	__( 'Chance of Rain' );
	__( 'Chance of Rain Showers' );
	__( 'Chance of Sleet ' );
	__( 'Chance of Snow' );
	__( 'Chance of Snow Showers' );
	__( 'Chance of Storms' );
	__( 'Clear' );
	__( 'Clearing' );
	__( 'Cloudy' );
	__( 'Drizzle' );
	__( 'Fair' );
	__( 'Flurries' );
	__( 'Fog' );
	__( 'Foggy' );
	__( 'Freezing Drizzle' );
	__( 'Freezing Rain' );
	__( 'Frozen Mix' );
	__( 'Hazy' );
	__( 'Headline' );
	__( 'Heavy Rain' );
	__( 'Heavy Snow' );
	__( 'Hot and Humid' );
	__( 'Increasing Clouds' );
	__( 'Light Snow' );
	__( 'Mostly Clear' );
	__( 'Mostly Cloudy' );
	__( 'Mostly Sunny' );
	__( 'Nowcast' );
	__( 'Partly Cloudy' );
	__( 'Partly Sunny' );
	__( 'Rain' );
	__( 'Rain Showers' );
	__( 'Scattered Showers' );
	__( 'Scattered Thunderstorms' );
	__( 'Sleet' );
	__( 'Snow' );
	__( 'Snow Showers' );
	__( 'Sunny' );
	__( 'Thunderstorms' );
	__( 'Unknown' );
	__( 'Very Cold' );
	__( 'Very Hot' );
	__( 'Warm and Humid' );
	__( 'Windy' );
}
