<?php
/**
 * Country related functionality.
 *
 * @package  FAIRE
 */

namespace Faire\Wc;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

/**
 * Country related functionality.
 */
class Country {

	/**
	 * Converts ISO ISO_3166-1 alpha-2 country codes to alpha-3.
	 *
	 * @param string $country_code ISO ISO_3166-1 alpha-2 country code.
	 *
	 * @return string the country code in ISO ISO_3166-1 alpha-3 format.
	 */
	public static function convert_country_iso2_to_iso3( string $country_code ): string {
		$country_codes = apply_filters(
			'faire_wc_country_iso2_to_iso3',
			array(
				'AF' => 'AFG', // Afghanistan.
				'AX' => 'ALA', // Aland Islands.
				'AL' => 'ALB', // Albania.
				'DZ' => 'DZA', // Algeria.
				'AS' => 'ASM', // American Samoa.
				'AD' => 'AND', // Andorra.
				'AO' => 'AGO', // Angola.
				'AI' => 'AIA', // Anguilla.
				'AQ' => 'ATA', // Antarctica.
				'AG' => 'ATG', // Antigua and Barbuda.
				'AR' => 'ARG', // Argentina.
				'AM' => 'ARM', // Armenia.
				'AW' => 'ABW', // Aruba.
				'AU' => 'AUS', // Australia.
				'AT' => 'AUT', // Austria.
				'AZ' => 'AZE', // Azerbaijan.
				'BS' => 'BHS', // Bahamas.
				'BH' => 'BHR', // Bahrain.
				'BD' => 'BGD', // Bangladesh.
				'BB' => 'BRB', // Barbados.
				'BY' => 'BLR', // Belarus.
				'BE' => 'BEL', // Belgium.
				'BZ' => 'BLZ', // Belize.
				'BJ' => 'BEN', // Benin.
				'BM' => 'BMU', // Bermuda.
				'BT' => 'BTN', // Bhutan.
				'BO' => 'BOL', // Bolivia.
				'BQ' => 'BES', // Bonaire, Saint Estatius and Saba.
				'BA' => 'BIH', // Bosnia and Herzegovina.
				'BW' => 'BWA', // Botswana.
				'BV' => 'BVT', // Bouvet Islands.
				'BR' => 'BRA', // Brazil.
				'IO' => 'IOT', // British Indian Ocean Territory.
				'BN' => 'BRN', // Brunei.
				'BG' => 'BGR', // Bulgaria.
				'BF' => 'BFA', // Burkina Faso.
				'BI' => 'BDI', // Burundi.
				'KH' => 'KHM', // Cambodia.
				'CM' => 'CMR', // Cameroon.
				'CA' => 'CAN', // Canada.
				'CV' => 'CPV', // Cape Verde.
				'KY' => 'CYM', // Cayman Islands.
				'CF' => 'CAF', // Central African Republic.
				'TD' => 'TCD', // Chad.
				'CL' => 'CHL', // Chile.
				'CN' => 'CHN', // China.
				'CX' => 'CXR', // Christmas Island.
				'CC' => 'CCK', // Cocos (Keeling) Islands.
				'CO' => 'COL', // Colombia.
				'KM' => 'COM', // Comoros.
				'CG' => 'COG', // Congo.
				'CD' => 'COD', // Congo, Democratic Republic of the.
				'CK' => 'COK', // Cook Islands.
				'CR' => 'CRI', // Costa Rica.
				'CI' => 'CIV', // Côte d\'Ivoire.
				'HR' => 'HRV', // Croatia.
				'CU' => 'CUB', // Cuba.
				'CW' => 'CUW', // Curaçao.
				'CY' => 'CYP', // Cyprus.
				'CZ' => 'CZE', // Czech Republic.
				'DK' => 'DNK', // Denmark.
				'DJ' => 'DJI', // Djibouti.
				'DM' => 'DMA', // Dominica.
				'DO' => 'DOM', // Dominican Republic.
				'EC' => 'ECU', // Ecuador.
				'EG' => 'EGY', // Egypt.
				'SV' => 'SLV', // El Salvador.
				'GQ' => 'GNQ', // Equatorial Guinea.
				'ER' => 'ERI', // Eritrea.
				'EE' => 'EST', // Estonia.
				'ET' => 'ETH', // Ethiopia.
				'FK' => 'FLK', // Falkland Islands.
				'FO' => 'FRO', // Faroe Islands.
				'FJ' => 'FIJ', // Fiji.
				'FI' => 'FIN', // Finland.
				'FR' => 'FRA', // France.
				'GF' => 'GUF', // French Guiana.
				'PF' => 'PYF', // French Polynesia.
				'TF' => 'ATF', // French Southern Territories.
				'GA' => 'GAB', // Gabon.
				'GM' => 'GMB', // Gambia.
				'GE' => 'GEO', // Georgia.
				'DE' => 'DEU', // Germany.
				'GH' => 'GHA', // Ghana.
				'GI' => 'GIB', // Gibraltar.
				'GR' => 'GRC', // Greece.
				'GL' => 'GRL', // Greenland.
				'GD' => 'GRD', // Grenada.
				'GP' => 'GLP', // Guadeloupe.
				'GU' => 'GUM', // Guam.
				'GT' => 'GTM', // Guatemala.
				'GG' => 'GGY', // Guernsey.
				'GN' => 'GIN', // Guinea.
				'GW' => 'GNB', // Guinea-Bissau.
				'GY' => 'GUY', // Guyana.
				'HT' => 'HTI', // Haiti.
				'HM' => 'HMD', // Heard Island and McDonald Islands.
				'VA' => 'VAT', // Holy See (Vatican City State).
				'HN' => 'HND', // Honduras.
				'HK' => 'HKG', // Hong Kong.
				'HU' => 'HUN', // Hungary.
				'IS' => 'ISL', // Iceland.
				'IN' => 'IND', // India.
				'ID' => 'IDN', // Indonesia.
				'IR' => 'IRN', // Iran.
				'IQ' => 'IRQ', // Iraq.
				'IE' => 'IRL', // Republic of Ireland.
				'IM' => 'IMN', // Isle of Man.
				'IL' => 'ISR', // Israel.
				'IT' => 'ITA', // Italy.
				'JM' => 'JAM', // Jamaica.
				'JP' => 'JPN', // Japan.
				'JE' => 'JEY', // Jersey.
				'JO' => 'JOR', // Jordan.
				'KZ' => 'KAZ', // Kazakhstan.
				'KE' => 'KEN', // Kenya.
				'KI' => 'KIR', // Kiribati.
				'KP' => 'PRK', // Korea, Democratic People's Republic of.
				'KR' => 'KOR', // Korea, Republic of (South).
				'KW' => 'KWT', // Kuwait.
				'KG' => 'KGZ', // Kyrgyzstan.
				'LA' => 'LAO', // Laos.
				'LV' => 'LVA', // Latvia.
				'LB' => 'LBN', // Lebanon.
				'LS' => 'LSO', // Lesotho.
				'LR' => 'LBR', // Liberia.
				'LY' => 'LBY', // Libya.
				'LI' => 'LIE', // Liechtenstein.
				'LT' => 'LTU', // Lithuania.
				'LU' => 'LUX', // Luxembourg.
				'MO' => 'MAC', // Macao S.A.R., China.
				'MK' => 'MKD', // Macedonia.
				'MG' => 'MDG', // Madagascar.
				'MW' => 'MWI', // Malawi.
				'MY' => 'MYS', // Malaysia.
				'MV' => 'MDV', // Maldives.
				'ML' => 'MLI', // Mali.
				'MT' => 'MLT', // Malta.
				'MH' => 'MHL', // Marshall Islands.
				'MQ' => 'MTQ', // Martinique.
				'MR' => 'MRT', // Mauritania.
				'MU' => 'MUS', // Mauritius.
				'YT' => 'MYT', // Mayotte.
				'MX' => 'MEX', // Mexico.
				'FM' => 'FSM', // Micronesia.
				'MD' => 'MDA', // Moldova.
				'MC' => 'MCO', // Monaco.
				'MN' => 'MNG', // Mongolia.
				'ME' => 'MNE', // Montenegro.
				'MS' => 'MSR', // Montserrat.
				'MA' => 'MAR', // Morocco.
				'MZ' => 'MOZ', // Mozambique.
				'MM' => 'MMR', // Myanmar.
				'NA' => 'NAM', // Namibia.
				'NR' => 'NRU', // Nauru.
				'NP' => 'NPL', // Nepal.
				'NL' => 'NLD', // Netherlands.
				'AN' => 'ANT', // Netherlands Antilles.
				'NC' => 'NCL', // New Caledonia.
				'NZ' => 'NZL', // New Zealand.
				'NI' => 'NIC', // Nicaragua.
				'NE' => 'NER', // Niger.
				'NG' => 'NGA', // Nigeria.
				'NU' => 'NIU', // Niue.
				'NF' => 'NFK', // Norfolk Island.
				'MP' => 'MNP', // Northern Mariana Islands.
				'NO' => 'NOR', // Norway.
				'OM' => 'OMN', // Oman.
				'PK' => 'PAK', // Pakistan.
				'PW' => 'PLW', // Palau.
				'PS' => 'PSE', // Palestinian Territory.
				'PA' => 'PAN', // Panama.
				'PG' => 'PNG', // Papua New Guinea.
				'PY' => 'PRY', // Paraguay.
				'PE' => 'PER', // Peru.
				'PH' => 'PHL', // Philippines.
				'PN' => 'PCN', // Pitcairn.
				'PL' => 'POL', // Poland.
				'PT' => 'PRT', // Portugal.
				'PR' => 'PRI', // Puerto Rico.
				'QA' => 'QAT', // Qatar.
				'RE' => 'REU', // Reunion.
				'RO' => 'ROU', // Romania.
				'RU' => 'RUS', // Russia.
				'RW' => 'RWA', // Rwanda.
				'BL' => 'BLM', // Saint Barthelemy.
				'SH' => 'SHN', // Saint Helena.
				'KN' => 'KNA', // Saint Kitts and Nevis.
				'LC' => 'LCA', // Saint Lucia.
				'MF' => 'MAF', // Saint Martin (French part).
				'SX' => 'SXM', // Sint Maarten / Saint Matin (Dutch part).
				'PM' => 'SPM', // Saint Pierre and Miquelon.
				'VC' => 'VCT', // Saint Vincent and the Grenadines.
				'WS' => 'WSM', // Samoa.
				'SM' => 'SMR', // San Marino.
				'ST' => 'STP', // Sao Tome and Principe.
				'SA' => 'SAU', // Saudi Arabia.
				'SN' => 'SEN', // Senegal.
				'RS' => 'SRB', // Serbia.
				'SC' => 'SYC', // Seychelles.
				'SL' => 'SLE', // Sierra Leone.
				'SG' => 'SGP', // Singapore.
				'SK' => 'SVK', // Slovakia.
				'SI' => 'SVN', // Slovenia.
				'SB' => 'SLB', // Solomon Islands.
				'SO' => 'SOM', // Somalia.
				'ZA' => 'ZAF', // South Africa.
				'GS' => 'SGS', // South Georgia/Sandwich Islands.
				'SS' => 'SSD', // South Sudan.
				'ES' => 'ESP', // Spain.
				'LK' => 'LKA', // Sri Lanka.
				'SD' => 'SDN', // Sudan.
				'SR' => 'SUR', // Suriname.
				'SJ' => 'SJM', // Svalbard and Jan Mayen.
				'SZ' => 'SWZ', // Swaziland.
				'SE' => 'SWE', // Sweden.
				'CH' => 'CHE', // Switzerland.
				'SY' => 'SYR', // Syria.
				'TW' => 'TWN', // Taiwan.
				'TJ' => 'TJK', // Tajikistan.
				'TZ' => 'TZA', // Tanzania.
				'TH' => 'THA', // Thailand.
				'TL' => 'TLS', // Timor-Leste.
				'TG' => 'TGO', // Togo.
				'TK' => 'TKL', // Tokelau.
				'TO' => 'TON', // Tonga.
				'TT' => 'TTO', // Trinidad and Tobago.
				'TN' => 'TUN', // Tunisia.
				'TR' => 'TUR', // Turkey.
				'TM' => 'TKM', // Turkmenistan.
				'TC' => 'TCA', // Turks and Caicos Islands.
				'TV' => 'TUV', // Tuvalu.
				'UG' => 'UGA', // Uganda.
				'UA' => 'UKR', // Ukraine.
				'AE' => 'ARE', // United Arab Emirates.
				'GB' => 'GBR', // United Kingdom.
				'US' => 'USA', // United States.
				'UM' => 'UMI', // United States Minor Outlying Islands.
				'UY' => 'URY', // Uruguay.
				'UZ' => 'UZB', // Uzbekistan.
				'VU' => 'VUT', // Vanuatu.
				'VE' => 'VEN', // Venezuela.
				'VN' => 'VNM', // Vietnam.
				'VG' => 'VGB', // Virgin Islands, British.
				'VI' => 'VIR', // Virgin Island, U.S..
				'WF' => 'WLF', // Wallis and Futuna.
				'EH' => 'ESH', // Western Sahara.
				'YE' => 'YEM', // Yemen.
				'ZM' => 'ZMB', // Zambia.
				'ZW' => 'ZWE', // Zimbabwe.
			)
		);
		return isset( $country_codes[ $country_code ] )
			? $country_codes[ $country_code ]
			: $country_code;
	}


	/**
	 * Converts ISO ISO_3166-1 alpha-3 country codes to alpha-2.
	 *
	 * @param string $country_code ISO ISO_3166-1 alpha-3 country code.
	 *
	 * @return string the country code in ISO ISO_3166-1 alpha-2 format.
	 */
	public static function convert_country_iso3_to_iso2( string $country_code ): string {
		$country_codes = apply_filters(
			'faire_wc_country_iso3_to_iso2',
			array(
				'AFG' => 'AF', // Afghanistan.
				'ALA' => 'AX', // Aland Islands.
				'ALB' => 'AL', // Albania.
				'DZA' => 'DZ', // Algeria.
				'ASM' => 'AS', // American Samoa.
				'AND' => 'AD', // Andorra.
				'AGO' => 'AO', // Angola.
				'AIA' => 'AI', // Anguilla.
				'ATA' => 'AQ', // Antarctica.
				'ATG' => 'AG', // Antigua and Barbuda.
				'ARG' => 'AR', // Argentina.
				'ARM' => 'AM', // Armenia.
				'ABW' => 'AW', // Aruba.
				'AUS' => 'AU', // Australia.
				'AUT' => 'AT', // Austria.
				'AZE' => 'AZ', // Azerbaijan.
				'BHS' => 'BS', // Bahamas.
				'BHR' => 'BH', // Bahrain.
				'BGD' => 'BD', // Bangladesh.
				'BRB' => 'BB', // Barbados.
				'BLR' => 'BY', // Belarus.
				'BEL' => 'BE', // Belgium.
				'BLZ' => 'BZ', // Belize.
				'BEN' => 'BJ', // Benin.
				'BMU' => 'BM', // Bermuda.
				'BTN' => 'BT', // Bhutan.
				'BOL' => 'BO', // Bolivia.
				'BES' => 'BQ', // Bonaire, Saint Estatius and Saba.
				'BIH' => 'BA', // Bosnia and Herzegovina.
				'BWA' => 'BW', // Botswana.
				'BVT' => 'BV', // Bouvet Islands.
				'BRA' => 'BR', // Brazil.
				'IOT' => 'IO', // British Indian Ocean Territory.
				'BRN' => 'BN', // Brunei.
				'BGR' => 'BG', // Bulgaria.
				'BFA' => 'BF', // Burkina Faso.
				'BDI' => 'BI', // Burundi.
				'KHM' => 'KH', // Cambodia.
				'CMR' => 'CM', // Cameroon.
				'CAN' => 'CA', // Canada.
				'CPV' => 'CV', // Cape Verde.
				'CYM' => 'KY', // Cayman Islands.
				'CAF' => 'CF', // Central African Republic.
				'TCD' => 'TD', // Chad.
				'CHL' => 'CL', // Chile.
				'CHN' => 'CN', // China.
				'CXR' => 'CX', // Christmas Island.
				'CCK' => 'CC', // Cocos (Keeling) Islands.
				'COL' => 'CO', // Colombia.
				'COM' => 'KM', // Comoros.
				'COG' => 'CG', // Congo.
				'COD' => 'CD', // Congo, Democratic Republic of the.
				'COK' => 'CK', // Cook Islands.
				'CRI' => 'CR', // Costa Rica.
				'CIV' => 'CI', // Côte d\'Ivoire.
				'HRV' => 'HR', // Croatia.
				'CUB' => 'CU', // Cuba.
				'CUW' => 'CW', // Curaçao.
				'CYP' => 'CY', // Cyprus.
				'CZE' => 'CZ', // Czech Republic.
				'DNK' => 'DK', // Denmark.
				'DJI' => 'DJ', // Djibouti.
				'DMA' => 'DM', // Dominica.
				'DOM' => 'DO', // Dominican Republic.
				'ECU' => 'EC', // Ecuador.
				'EGY' => 'EG', // Egypt.
				'SLV' => 'SV', // El Salvador.
				'GNQ' => 'GQ', // Equatorial Guinea.
				'ERI' => 'ER', // Eritrea.
				'EST' => 'EE', // Estonia.
				'ETH' => 'ET', // Ethiopia.
				'FLK' => 'FK', // Falkland Islands.
				'FRO' => 'FO', // Faroe Islands.
				'FIJ' => 'FJ', // Fiji.
				'FIN' => 'FI', // Finland.
				'FRA' => 'FR', // France.
				'GUF' => 'GF', // French Guiana.
				'PYF' => 'PF', // French Polynesia.
				'ATF' => 'TF', // French Southern Territories.
				'GAB' => 'GA', // Gabon.
				'GMB' => 'GM', // Gambia.
				'GEO' => 'GE', // Georgia.
				'DEU' => 'DE', // Germany.
				'GHA' => 'GH', // Ghana.
				'GIB' => 'GI', // Gibraltar.
				'GRC' => 'GR', // Greece.
				'GRL' => 'GL', // Greenland.
				'GRD' => 'GD', // Grenada.
				'GLP' => 'GP', // Guadeloupe.
				'GUM' => 'GU', // Guam.
				'GTM' => 'GT', // Guatemala.
				'GGY' => 'GG', // Guernsey.
				'GIN' => 'GN', // Guinea.
				'GNB' => 'GW', // Guinea-Bissau.
				'GUY' => 'GY', // Guyana.
				'HTI' => 'HT', // Haiti.
				'HMD' => 'HM', // Heard Island and McDonald Islands.
				'VAT' => 'VA', // Holy See (Vatican City State).
				'HND' => 'HN', // Honduras.
				'HKG' => 'HK', // Hong Kong.
				'HUN' => 'HU', // Hungary.
				'ISL' => 'IS', // Iceland.
				'IND' => 'IN', // India.
				'IDN' => 'ID', // Indonesia.
				'IRN' => 'IR', // Iran.
				'IRQ' => 'IQ', // Iraq.
				'IRL' => 'IE', // Republic of Ireland.
				'IMN' => 'IM', // Isle of Man.
				'ISR' => 'IL', // Israel.
				'ITA' => 'IT', // Italy.
				'JAM' => 'JM', // Jamaica.
				'JPN' => 'JP', // Japan.
				'JEY' => 'JE', // Jersey.
				'JOR' => 'JO', // Jordan.
				'KAZ' => 'KZ', // Kazakhstan.
				'KEN' => 'KE', // Kenya.
				'KIR' => 'KI', // Kiribati.
				'PRK' => 'KP', // Korea, Democratic People's Republic of.
				'KOR' => 'KR', // Korea, Republic of (South).
				'KWT' => 'KW', // Kuwait.
				'KGZ' => 'KG', // Kyrgyzstan.
				'LAO' => 'LA', // Laos.
				'LVA' => 'LV', // Latvia.
				'LBN' => 'LB', // Lebanon.
				'LSO' => 'LS', // Lesotho.
				'LBR' => 'LR', // Liberia.
				'LBY' => 'LY', // Libya.
				'LIE' => 'LI', // Liechtenstein.
				'LTU' => 'LT', // Lithuania.
				'LUX' => 'LU', // Luxembourg.
				'MAC' => 'MO', // Macao S.A.R., China.
				'MKD' => 'MK', // Macedonia.
				'MDG' => 'MG', // Madagascar.
				'MWI' => 'MW', // Malawi.
				'MYS' => 'MY', // Malaysia.
				'MDV' => 'MV', // Maldives.
				'MLI' => 'ML', // Mali.
				'MLT' => 'MT', // Malta.
				'MHL' => 'MH', // Marshall Islands.
				'MTQ' => 'MQ', // Martinique.
				'MRT' => 'MR', // Mauritania.
				'MUS' => 'MU', // Mauritius.
				'MYT' => 'YT', // Mayotte.
				'MEX' => 'MX', // Mexico.
				'FSM' => 'FM', // Micronesia.
				'MDA' => 'MD', // Moldova.
				'MCO' => 'MC', // Monaco.
				'MNG' => 'MN', // Mongolia.
				'MNE' => 'ME', // Montenegro.
				'MSR' => 'MS', // Montserrat.
				'MAR' => 'MA', // Morocco.
				'MOZ' => 'MZ', // Mozambique.
				'MMR' => 'MM', // Myanmar.
				'NAM' => 'NA', // Namibia.
				'NRU' => 'NR', // Nauru.
				'NPL' => 'NP', // Nepal.
				'NLD' => 'NL', // Netherlands.
				'ANT' => 'AN', // Netherlands Antilles.
				'NCL' => 'NC', // New Caledonia.
				'NZL' => 'NZ', // New Zealand.
				'NIC' => 'NI', // Nicaragua.
				'NER' => 'NE', // Niger.
				'NGA' => 'NG', // Nigeria.
				'NIU' => 'NU', // Niue.
				'NFK' => 'NF', // Norfolk Island.
				'MNP' => 'MP', // Northern Mariana Islands.
				'NOR' => 'NO', // Norway.
				'OMN' => 'OM', // Oman.
				'PAK' => 'PK', // Pakistan.
				'PLW' => 'PW', // Palau.
				'PSE' => 'PS', // Palestinian Territory.
				'PAN' => 'PA', // Panama.
				'PNG' => 'PG', // Papua New Guinea.
				'PRY' => 'PY', // Paraguay.
				'PER' => 'PE', // Peru.
				'PHL' => 'PH', // Philippines.
				'PCN' => 'PN', // Pitcairn.
				'POL' => 'PL', // Poland.
				'PRT' => 'PT', // Portugal.
				'PRI' => 'PR', // Puerto Rico.
				'QAT' => 'QA', // Qatar.
				'REU' => 'RE', // Reunion.
				'ROU' => 'RO', // Romania.
				'RUS' => 'RU', // Russia.
				'RWA' => 'RW', // Rwanda.
				'BLM' => 'BL', // Saint Barthelemy.
				'SHN' => 'SH', // Saint Helena.
				'KNA' => 'KN', // Saint Kitts and Nevis.
				'LCA' => 'LC', // Saint Lucia.
				'MAF' => 'MF', // Saint Martin (French part).
				'SXM' => 'SX', // Sint Maarten / Saint Matin (Dutch part).
				'SPM' => 'PM', // Saint Pierre and Miquelon.
				'VCT' => 'VC', // Saint Vincent and the Grenadines.
				'WSM' => 'WS', // Samoa.
				'SMR' => 'SM', // San Marino.
				'STP' => 'ST', // Sao Tome and Principe.
				'SAU' => 'SA', // Saudi Arabia.
				'SEN' => 'SN', // Senegal.
				'SRB' => 'RS', // Serbia.
				'SYC' => 'SC', // Seychelles.
				'SLE' => 'SL', // Sierra Leone.
				'SGP' => 'SG', // Singapore.
				'SVK' => 'SK', // Slovakia.
				'SVN' => 'SI', // Slovenia.
				'SLB' => 'SB', // Solomon Islands.
				'SOM' => 'SO', // Somalia.
				'ZAF' => 'ZA', // South Africa.
				'SGS' => 'GS', // South Georgia/Sandwich Islands.
				'SSD' => 'SS', // South Sudan.
				'ESP' => 'ES', // Spain.
				'LKA' => 'LK', // Sri Lanka.
				'SDN' => 'SD', // Sudan.
				'SUR' => 'SR', // Suriname.
				'SJM' => 'SJ', // Svalbard and Jan Mayen.
				'SWZ' => 'SZ', // Swaziland.
				'SWE' => 'SE', // Sweden.
				'CHE' => 'CH', // Switzerland.
				'SYR' => 'SY', // Syria.
				'TWN' => 'TW', // Taiwan.
				'TJK' => 'TJ', // Tajikistan.
				'TZA' => 'TZ', // Tanzania.
				'THA' => 'TH', // Thailand.
				'TLS' => 'TL', // Timor-Leste.
				'TGO' => 'TG', // Togo.
				'TKL' => 'TK', // Tokelau.
				'TON' => 'TO', // Tonga.
				'TTO' => 'TT', // Trinidad and Tobago.
				'TUN' => 'TN', // Tunisia.
				'TUR' => 'TR', // Turkey.
				'TKM' => 'TM', // Turkmenistan.
				'TCA' => 'TC', // Turks and Caicos Islands.
				'TUV' => 'TV', // Tuvalu.
				'UGA' => 'UG', // Uganda.
				'UKR' => 'UA', // Ukraine.
				'ARE' => 'AE', // United Arab Emirates.
				'GBR' => 'GB', // United Kingdom.
				'USA' => 'US', // United States.
				'UMI' => 'UM', // United States Minor Outlying Islands.
				'URY' => 'UY', // Uruguay.
				'UZB' => 'UZ', // Uzbekistan.
				'VUT' => 'VU', // Vanuatu.
				'VEN' => 'VE', // Venezuela.
				'VNM' => 'VN', // Vietnam.
				'VGB' => 'VG', // Virgin Islands, British.
				'VIR' => 'VI', // Virgin Island, U.S..
				'WLF' => 'WF', // Wallis and Futuna.
				'ESH' => 'EH', // Western Sahara.
				'YEM' => 'YE', // Yemen.
				'ZMB' => 'ZM', // Zambia.
				'ZWE' => 'ZW', // Zimbabwe.
			)
		);
		return isset( $country_codes[ $country_code ] )
			? $country_codes[ $country_code ]
			: $country_code;
	}

}
