<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Cake\\Utility\\' => array($vendorDir . '/cakephp/utility'),
    'Cake\\Core\\' => array($vendorDir . '/cakephp/core'),
    'Cake\\Cache\\' => array($vendorDir . '/cakephp/cache'),
);
