<html>
<head>
    <style type="text/css">
        html, body, div, form, fieldset, legend, label, ol, ul {
            margin: 0;
            padding: 0;
            color: #444;
            font-family: "Open Sans",sans-serif;
            font-size: 13px;
            line-height: 1.4em;
        }
        table {
            border-collapse: collapse;
            border-spacing: 0;
        }
        th, td {
            text-align: left;
            vertical-align: top;
        }
        h1, h2, h3, h4, h5, h6, th, td, caption { font-weight:normal; }
        img { border: 0; }
        .result-good {
            background-color: #32cd32;
            color: #ffffff;
            padding: 4px 6px;
        }
        .result-bad {
            background-color: #ff0000;
            color: #ffffff;
            padding: 4px 6px;
        }
        ol#test-results li {
            border-bottom: 1px solid #ccc;
            margin-bottom: 15px;
        }
        .result-bad-msg {
            margin-top: 8px;
        }
        .fix-link {
            display: inline-block;
            text-decoration: none;
            font-size: 13px;
            line-height: 26px;
            height: 28px;
            margin: 0;
            padding: 0 10px 1px;
            cursor: pointer;
            border-width: 1px;
            border-style: solid;
            -webkit-appearance: none;
            -webkit-border-radius: 3px;
            border-radius: 3px;
            white-space: nowrap;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;

            color: #555;
            border-color: #ccc;
            background: #f7f7f7;
            -webkit-box-shadow: inset 0 1px 0 #fff,0 1px 0 rgba(0,0,0,.08);
            box-shadow: inset 0 1px 0 #fff,0 1px 0 rgba(0,0,0,.08);
            vertical-align: top;

            margin-top: 10px;
        }
        body {
            padding: 20px 35px;
        }
    </style>
</head>
<body>
<p><?php echo $this->message; ?></p><br><br>
<a href="<?php echo $this->urlIndex; ?>" class="fix-link"><?php _e('Perform selftest again', 'ifw'); ?></a>
</body>
</html>