<?php

$stichiatitlo = 'AlphaOmega Captcha & Anti-Spam Filter 設定';
$prindose = '<span style="color:#000080;">AlphaOmega Captcha & Anti-Spam Filter</span> 効果的であり、ユーザー コメント不適切なコンテンツを簡単に使用できるキャプチャとスパム（迷惑メール）・ フィルターをブロックするスパム対策のプラグイン。このプラグインは、管理ログでページの自動攻撃も阻止できます。<div style="padding-top:10px;">以下に示す既定の設定は高レベルのスパムや悪意のある管理者ログイン ページの攻撃に対する保護を提供します。また、追加のカスタマイズされたプラグインの動作をする場合の既定の設定を調整するオプションがあります。';
$dosetitlo = '寄付をご検討下さい';
$doseshpeel = '任意の方法で便利な場合は、この無料のプラグインの開発継続をサポートするために小額の寄付を提供することを検討する場合 <span style="color:#000080;">AlphaOmega Captcha & Anti-Spam Filter</span> クリエイター非常に感謝しました。任意寄付金額を謙虚に高く評価されます。ありがとう。';
$doseinput = '<input type="hidden" name="country" value="JP" ><input type="hidden" name="item_name" value="AlphaOmega Captcha & Anti-Spam Filterの寄付"><input type="hidden" name="currency_code" value="JPY">';
$dosekubitext = '寄付をして下さい';
$doseoutput = '<option value="500">&nbsp;500円 &nbsp; &nbsp;</option><option value="1000">&nbsp;1000円 &nbsp; &nbsp;</option><option value="1500">&nbsp;1500円 &nbsp; &nbsp;</option><option value="2000">&nbsp;2000円 &nbsp; &nbsp;</option><option value="2500">&nbsp;2500円 &nbsp; &nbsp;</option><option value="5000">&nbsp;5000円 &nbsp; &nbsp;</option>';
$dosepp = 'PayPal によって処理の寄付';
$stepglossa = '言語';
$stepglossaena = '英語';
$stepglossaenashpeel = 'この設定パネル内のすべてのテキストとするキャプチャ画像の横のテキストは英語でされます。';
$stepglossadio = '日本語';
$stepglossadioshpeel = 'この設定パネル内のすべてのテキストとするキャプチャ画像の横のテキストは日本語でされます。';
$stepglossatria = 'ギリシャ語';
$stepglossatriashpeel = 'この設定パネル内のすべてのテキストとするキャプチャ画像の横のテキストはギリシャ語でされます。';
$stepglossatesera = '韓国語';
$stepglossateserashpeel = 'この設定パネル内のすべてのテキストとするキャプチャ画像の横のテキストは韓国語でされます。';
$stepglossapente = '中国語';
$stepglossapenteshpeel = 'この設定パネル内のすべてのテキストとするキャプチャ画像の横のテキストは中国語でされます。';
$stepcaptype = 'キャプチャの種類';
$stepcaptypeena = 'さまざまなアルファベット順と数値文字を入力する必要があります。';
$stepcaptypedio = '単純な数学的なタスクを実行する必要があります。';
$stepcaptypetria = 'ユーザーは、アーティストの名前を入力する必要があります。';
$stepcaptypetesera = '有名な映画のタイトルを入力する必要があります。';
$stepcaptypepente = 'ユーザーは、作成者の名前を入力する必要があります。';
$stepcaptypeexi = '科学的な質問やクイズに答える必要があります。';
$stepcaptypeefta = '有名な歴史上の人物の名前を入力する必要があります。';
$stepcaptypeochto = '共通の頭字語で表される単語を入力する必要があります。';
$stepcaptypeenea = 'ユーザーは、音楽用語または表示器を入力する必要があります。';
$stepcaptypedeca = '首都または地理的な場所の名前を入力する必要があります。';
$stepcaptypeendeca = '単語接頭辞の数値の意味は、ユーザーが入力する必要があります。';
$stepcaptypedodeca = 'ユーザーに示す人と関連付けられるスポーツを入力する必要があります。';
$stepcaptypedecatria = '示す映画監督、映画監督の名前を入力する必要があります。';
$stepcaptypedecatesera = 'または項目に示すファッション用語の名前を入力する必要があります。';
$stepcaptypedecapente = '表示通貨に関連する国の名前をユーザーが必要です。';
$stepcaptypedecaexi = '項目に示すような食品の起源の国の名前をユーザーが必要です。';
$stepcaptypedecaefta = 'ユーザーは、医療の名前や表示用語を入力する必要です。';
$stepcaptypedecaochto = '示す生態学的用語を入力するユーザーが必要です。';
$stepcaptypedecaenea = 'ユーザーのよく知られているテレビ番組の名前を入力する必要があります。';
$stepcaptopos = 'キャプチャのページの場所';
$stepcaptoposcomm = 'コメント フォーム';
$stepcaptoposcommshpeel = 'キャプチャは、あなたのコメント フォームに表示されます。このキャプチャは、あなたのブログの記事の 1 つを訪問した後、コメントを投稿することを希望するユーザーによって完了される必要があります。';
$stepcaptoposadmin = 'A管理者ログイン ページ';
$stepcaptoposadminshpeel = 'キャプチャは、あなたの管理者ページにログインが表示されます。このキャプチャは、あなたの ワードプレスのアカウントにログインすることを希望するユーザーによって完了される必要があります/ダッシュ ボード。';
$stepcapepanomesikato = 'キャプチャの位置';
$stepcapepanomesikatoshpeel = 'あなたのワードプレスの記事とページのフォームのいずれか 3 つのポジションに設定できますコメント AlphaOmega キャプチャの位置します: <span style="letter-spacing:1.2px;color:#000080;">上</span>, <span style="letter-spacing:1.2px;color:#000080;">中</span>, 又は <span style="letter-spacing:1.2px;color:#000080;">下</span>。 AlphaOmega キャプチャ管理者ログイン ページ上の位置を<span style="letter-spacing:1.2px;color:#000080;">下</span>の位置に固定です。<div style="padding-top:10px;">ご希望のコメント フォーム キャプチャ位置を選択して下さい';
$stepcapepanomesikatotablecommtitle = 'コメント フォーム';
$stepcapepanomesikatotableadmintitle = '管理者ログイン';
$stepcapepanomesikatotablecommepano = '上';
$stepcapepanomesikatotablecommmesi = '中';
$stepcapepanomesikatotablecommkato = '下';
$stepcapepanomesikatotablecommkubi = 'コメントをおくる';
$stepcapepanomesikatotableadminkato = '下';
$stepcapepanomesikatotableadminkubi = 'ログイン';
$stepstragise = 'スパムフィルター';
$stepstragisepreshpeel = '標準のワードプレスのコメント フォームには名、メール、URL、およびコメントやメッセージなどのいくつかのフォーム要素が含まれています。<p>これらのフォーム要素はあなたのコメント フォームに存在する場合、このプラグインの設定内容をチェックまたは可能なスパムをフィルターする要素を選択することができます。コメント投稿のスパム関連のキーワードまたは語句 (以下で <span style="letter-spacing:1.2px;color:#000080;">スパムフィルターのリスト</span> 構成) を含むブロック、されが送信されません。</p><p>これは自動と手動のスパムを執拗な攻撃を阻止する、したがって不要で迷惑なスパム関連のコメントを殺到されてからあなたのワードプレスの管理領域を解放する非常に効果的な方法をすることができます。</p>';
$stepstragisetitlo = 'スパムをフィルターするには、コメント フォーム要素を選択します';
$stepstragiseonoma = '名前';
$stepstragisediefthinsi = 'メール';
$stepstragisehitaftafpi = 'URL';
$stepstragiseminima = 'コメント / メッセージ';
$stepstragisepostshpeel = 'スパム フィルター リストを構成します:</span><div style="padding-top:8px;"><span style="letter-spacing:1.2px;color:#000080;">既定のスパム フィルター リスト</span>を使用またはコメント提出スパムに関連するコンテンツを確認するには、<span style="letter-spacing:1.2px;color:#000080;">カスタム スパム フィルター リスト</span> を作成することができます。<p><span style="letter-spacing:1.2px;color:#000080;">カスタム スパム フィルター リスト</span>をするのには、<span style="letter-spacing:1.2px;color:#000080;">スパムフィルターを無効にします</span>ボタンをクリックし、スパムのキーワードやフレーズのリスト ボックスを入力します。各キーワードまたはフレーズを別々 の行がある必要があります。</p><p><strong>スパムフィルター</strong>は、自動的にすべての大文字と小文字の変化のリストで現在のキーワード/フレーズの世話をします。したがって、<span style="letter-spacing:1.2px;color:#000080;">Yellow Hat</span>、<span style="letter-spacing:1.2px;color:#000080;">yellow hat</span> に 2 つの別々 の行に追加するには冗長かつ不必要です。のみ、たとえば、<span style="letter-spacing:1.2px;color:#000080;">yellow hat</span> を 1 行追加する必要があります。</p><p>最後に、複数のフォームのキーワード/フレーズを使用しないでください - <span style="letter-spacing:1.2px;color:#000080;">yellow hats</span> ではなく <span style="letter-spacing:1.2px;color:#000080;">yellow hat</span> を使用します。</p><p><span style="letter-spacing:1.2px;color:#000080;">カスタム スパム フィルター リスト</span> を完了すると、<span style="letter-spacing:1.2px;color:#000080;">変更を保存します</span> ボタン をクリックします (手順 6)。キーワード/フレーズを追加または <span style="letter-spacing:1.2px;color:#000080;">カスタム スパム フィルター リスト</span> からいつでも削除することができます、あなたの変更のリスト <span style="letter-spacing:1.2px;color:#000080;">変更を保存します</span> (手順 6) をクリックして保存できます。</p><div style="color:#a80000;padding-top:7px;padding-bottom:10px;">あなたのコメントのスパムをフィルタ リングしない場合は、単に上記のすべてのコメントのフォーム要素をオフまたは <span style="letter-spacing:1.2px;color:#000080;">スパムフィルターを無効にします</span> ボタンをクリックします。';
$stepstragiseremovelistkubi = '       スパムフィルターを無効にします        ';
$stragismakoutivathos = '310';
$stepstragisedefaultlistkubi = '  既定のスパムフィルター リストを使用します  ';
$stepstragisecustomlistkubi = ' カスタムスパムフィルター リストを使用します';
$stepstragisemessagepreshpeel = 'スパマーに表示される警告メッセージをカスタマイズします:</span><div style="padding-top:8px;">あなたは、彼らがあなたの ウェブサイトを通じてコメントを投稿してスパムを送信しようとするとがスパム送信者に表示されるメッセージをカスタマイズするオプションがあります。</div></div></td></tr><tr><td height="15px;"></td></tr><tr><td valign="top"><table cellpadding="0" cellspacing="0" border="0"><tr><td><div style="padding-left:15px;padding-right:15px;padding-top:10px;letter-spacing:1.2px;">&nbsp;スパマーに示す現在の警告メッセージ:';
$stepstragisemessagepostshpeel = 'スパマーのための新しい警告メッセージを設定します:</div></td></tr><tr><td align="left"style="padding:15px;padding-top:10px;"><span style="font-weight:bold;padding-left:5px;">メッセージのタイトル: (太字で表示されます)</span><div style="padding-top:5px;padding-left:5px;"><input type="text" name="kakofanititlo" style="width:400px;font-weight:bold;" maxlength="100"></div></td></tr><tr><td align="left"style="padding:15px;padding-top:5px;">
<span style="font-weight:bold;padding-left:5px;">メッセージの内容';
$stepstragiseusedefaultkubi = '既定のスパム メッセージを使用します';
$stepsave = '変更を保存します';
$stepsaveshpeel = 'あなたのプラグインの設定を変更した場合は、<span style="letter-spacing:1.2px;color:#000080;">変更を保存します</span> ボタンをクリックして下さい。';
$stepsavesavekubi = '変更を保存します';
$stepsaverestoredefaultkubi = '既定の設定を復元します';
$stepfeedback = 'フィードバック';
$stepfeedbackpreshpeel = 'あなたのフィードバックを大幅にいただければ幸いです。<p>改善の提案を含むこのワードプレスのプラグインの使用に関する感想があるあれば <span style="letter-spacing:1.2px;color:#000080;">フィードバック</span> ボタンをクリックしてください。</p>';
$stepfeedbackpostshpeel = '<strong>AlphaOmega Captcha & Anti-Spam Filter</strong>を使用していただきありがとうございます。';

?>
