<?php

$stichiatitlo = 'AlphaOmega Captcha & Anti-Spam Filter 설정';
$prindose = '<span style="color:#000080;">AlphaOmega Captcha & Anti-Spam Filter</span>는 효과적 이며 부적절 한 콘텐츠에 대 한 사용자 의견을 게시 하는 사용 하기 간단 captcha 및 스팸 필터를 차단 하는 스팸 방지 플러그인. 이 플러그인에는 관리 로그인 페이지에 대 한 자동화 된 공격 막아 낼 수 있습니다.<div style="padding-top:10px;">기본 설정 아래의 스팸 및 악의적인 관리자 로그인 페이지에 공격에 대 한 보호의 높은 수준을 제공 합니다. 추가 사용자 지정된 플러그인 동작을 원하는 경우 기본 설정을 조정 하는 옵션도 있습니다.';
$dosetitlo = '기부 고려 하시기 바랍니다';
$doseshpeel = '<span style="color:#000080;">AlphaOmega Captcha & Anti-Spam Filter</span>의 창조 자 매우 많이 제공 하는 경우에 당신이 그것을 어떤 방식으로 유용 하 게 찾을이 무료 플러그인의 지속적인된 개발을 지 원하는 데 도움이 작은 기부를 고려할 것 이라고 하는 경우 그것을 이해할 것 이다. 모든 기부 금액을 겸허 하 게 인정 될 것 이다. 감사합니다.';
$doseinput = '<input type="hidden" name="item_name" value="AlphaOmega Captcha & Anti-Spam Filter에 대 한 기부"><input type="hidden" name="currency_code" value="USD">';
$dosekubitext = '제발 기부';
$doseoutput = '<option value="5">&nbsp;$5 &nbsp; &nbsp;</option><option value="10">&nbsp;$10 &nbsp; &nbsp;</option><option value="15">&nbsp;$15 &nbsp; &nbsp;</option><option value="20">&nbsp;$20 &nbsp; &nbsp;</option><option value="25">&nbsp;$25 &nbsp; &nbsp;</option><option value="50">&nbsp;$50 &nbsp; &nbsp;</option>';
$dosepp = 'PayPal에서 처리 하는 기부금';
$stepglossa = '언어';
$stepglossaena = '영어';
$stepglossaenashpeel = '이 설정 패널에서 모든 텍스트와 captcha 이미지를 인접 한 텍스트 영어 언어에 있을 것입니다.';
$stepglossadio = '일본어';
$stepglossadioshpeel = '이 설정 패널에서 모든 텍스트 및 텍스트 captcha 이미지에 인접 한 일본어에 있을 것입니다.';
$stepglossatria = '그리스어';
$stepglossatriashpeel = '이 설정 패널에서 모든 텍스트 및 텍스트 captcha 이미지에 인접 한 그리스어 언어에 있을 것입니다.';
$stepglossatesera = '한국어';
$stepglossateserashpeel = '이 설정 패널에서 모든 텍스트 및 텍스트 captcha 이미지에 인접 한 한국 언어에 있을 것입니다.';
$stepglossapente = '중국어';
$stepglossapenteshpeel = '이 설정 패널에서 모든 텍스트 및 텍스트 captcha 이미지에 인접 한 중국 언어에 있을 것입니다.';
$stepcaptype = 'Captcha 유형';
$stepcaptypeena = '사용자가 다양 한 알파벳 문자와 숫자 문자를 입력 해야 합니다.';
$stepcaptypedio = '간단한 수학 작업을 수행 하는 사용자가 필요 합니다.';
$stepcaptypetria = '사용자는 작가의 이름을 입력 해야 합니다.';
$stepcaptypetesera = '사용자가 잘 알려진 영화 제목을 입력 해야 합니다.';
$stepcaptypepente = '사용자는 만든이의 이름을 입력 해야 합니다.';
$stepcaptypeexi = '과학적 질문 또는 퀴즈에 대 한 대답을 입력 하는 사용자가 필요 합니다.';
$stepcaptypeefta = '유명한 역사적 인물의 이름을 입력 하는 사용자가 필요 합니다.';
$stepcaptypeochto = '사용자를 일반적인 약어 표현 하는 단어를 입력 해야 합니다.';
$stepcaptypeenea = '사용자는 음악 용어 또는 악기 표시를 입력 해야 합니다.';
$stepcaptypedeca = '자본 도시 또는 지리적 장소 이름을 입력 하는 사용자가 필요 합니다.';
$stepcaptypeendeca = '사용자 단어 접두사의 숫자 의미를 입력 해야 합니다.';
$stepcaptypedodeca = '사용자는 표시 하는 사용자와 관련 된 스포츠를 입력 해야 합니다.';
$stepcaptypedecatria = '사용자가 표시 된 영화 감독 누가 영화 감독의 이름을 입력 해야 합니다.';
$stepcaptypedecatesera = '패션 용어의 이름 또는 표시 된 항목을 입력 하는 사용자가 필요 합니다.';
$stepcaptypedecapente = '사용자가 표시 된 통화와 관련 된 국가 필요 합니다.';
$stepcaptypedecaexi = '사용자 항목 표시 식품의 원산지가 필요 합니다.';
$stepcaptypedecaefta = '의료 또는 표시 하는 용어를 입력 하는 사용자 필요 합니다.';
$stepcaptypedecaochto = '사용자가 표시 된 생태 용어 입력 해야 합니다.';
$stepcaptypedecaenea = '잘 알려진 TV 프로그램의 이름을 입력 하는 데 필요한 사용자.';
$stepcaptopos = 'Captcha 페이지 위치';
$stepcaptoposcomm = '코멘트 양식';
$stepcaptoposcommshpeel = 'Captcha는 코멘트 양식에 표시 됩니다. 이 captcha이 귀하의 블로그 게시물 중 하나를 방문한 후에 의견을 게시 하고자 사용자가 완료 해야 합니다.';
$stepcaptoposadmin = '관리자 로그인 페이지';
$stepcaptoposadminshpeel = 'Captcha는 관리자 로그인 페이지에 표시 됩니다. 이 captcha이 Wordpress 계정에 로그인 하고자 사용자가 완료 해야 할 / 대시보드.';
$stepcapepanomesikato = 'Captcha 위치';
$stepcapepanomesikatoshpeel = '세 가지 위치 중 하나에 Wordpress 게시물 및 페이지의 형태를 설정할 수 있습니다 코멘트에 배치 하는 AlphaOmega captcha의 위치: <span style="letter-spacing:1.2px;color:#000080;">맨 위로</span> ( T ), <span style="letter-spacing:1.2px;color:#000080;">중간</span> ( M ), 또는 <span style="letter-spacing:1.2px;color:#000080;">아래쪽 ( B )</span>. 관리자 로그인 페이지에 AlphaOmega captcha의 위치는 하단에 위치에 고정 됩니다.<div style="padding-top:10px;">원하는 코멘트 양식에 captcha 위치를 선택 하십시오.';
$stepcapepanomesikatotablecommtitle = '코멘트 양식';
$stepcapepanomesikatotableadmintitle = '관리자 로그인 페이지';
$stepcapepanomesikatotablecommepano = 'T';
$stepcapepanomesikatotablecommmesi = 'M';
$stepcapepanomesikatotablecommkato = 'B';
$stepcapepanomesikatotablecommkubi = '댓글 보내기';
$stepcapepanomesikatotableadminkato = 'B';
$stepcapepanomesikatotableadminkubi = '로그인';
$stepstragise = '스팸 방지 필터';
$stepstragisepreshpeel = '표준 Wordpress 코멘트 양식 이름, 메일, URL 및 코멘트 또는 메시지와 같은 여러 가지 양식 요소를 포함합니다.<p>이러한 양식 요소 코멘트 폼에 있는 경우이 플러그인 설정을 사용 하면 확인 하거나 가능한 스팸 필터링 하고자 하는 내용이 요소를 선택할 수 있습니다. 의견 제출 포함 된 스팸 관련 키워드 또는 문구 (아래는 <span style="letter-spacing:1.2px;color:#000080;">스팸 필터 목록</span>에 구성)을 차단 하 고 당신에 게 전송 되지 것입니다.</p><p>이 잔인 한 자동 및 수동 스팸 공격을 저지 하 고 따라서 귀하의 Wordpress 관리 영역에서 원치 않는 성가신 스팸 관련 코멘트와 침수 되 고 무료 매우 효과적인 방법일 수 있다.</p>';
$stepstragisetitlo = '스팸 필터링 하려면 코멘트 폼 요소 선택';
$stepstragiseonoma = '이름';
$stepstragisediefthinsi = '메일 주소';
$stepstragisehitaftafpi = 'URL';
$stepstragiseminima = '코멘트 / 메시지';
$stepstragisepostshpeel = '스팸 필터 목록 구성:</span><div style="padding-top:8px;"><span style="letter-spacing:1.2px;color:#000080;">기본 스팸 필터 목록</span>을 사용 하거나 스팸 관련 콘텐츠에 대 한 의견 제출 확인 자신의 <span style="letter-spacing:1.2px;color:#000080;">사용자 지정 스팸 필터 목록</span>를 만들 수 있습니다.<p>자신의 <span style="letter-spacing:1.2px;color:#000080;">사용자 지정 스팸 필터 목록</span>를 만들려면 <span style="letter-spacing:1.2px;color:#000080;">스팸 필터를 해제 </span> 단추를 클릭 하 고 목록 상자 아래에 스팸 관련 키워드 및 어구를 입력 합니다. 각 키워드 또는 어구는 별도 줄에 있어야 합니다.</p><p><strong>스팸 방지 필터</strong> 자동으로 돌의 키워드/구문 목록에 모든 대문자 및 소문자 변형. 따라서, 중복 및 불필요 한은 <span style="letter-spacing:1.2px;color:#000080;">Yellow Hat</span> 및 <span style="letter-spacing:1.2px;color:#000080;">yellow hat</span> 두 별도 줄에 추가 합니다. 예를 들어, 한 줄에 <span style="letter-spacing:1.2px;color:#000080;">yellow hat</span>을 추가 해야 합니다.</p><p>--마지막으로, 키워드/문구의 복수 형태를 사용 하지 마십시오-<span style="letter-spacing:1.2px;color:#000080;">yellow hat</span> <span style="letter-spacing:1.2px;color:#000080;">yellow hats</span> 대신 사용 하 여.</p><p>일단 귀하의  <span style="letter-spacing:1.2px;color:#000080;">사용자 지정 스팸 필터 목록</span>를 만든, <span style="letter-spacing:1.2px;color:#000080;">변경 내용을 저장합니다</span> 단추 (6 단계) 사용자 지정 목록 저장을 클릭 합니다. 키워드/문구를 추가할 수 있습니다 또는 귀하의  <span style="letter-spacing:1.2px;color:#000080;">사용자 지정 스팸 필터 목록</span>에서 언제 든 지 삭제와 수정된 목록 (6 단계) <span style="letter-spacing:1.2px;color:#000080;">변경 내용을 저장합니다</span> 단추를 클릭 하 여 저장할 수 있습니다. 
</p><div style="color:#a80000;padding-top:7px;padding-bottom:10px;">스팸에 대 한 귀하의 의견을 필터링 하지 않으려면 단순히 위의 모든 코멘트 양식 요소를 선택을 취소 하거나 <span style="letter-spacing:1.2px;color:#000080;">스팸 필터를 해제</span> 단추를 클릭 합니다.';
$stepstragiseremovelistkubi = '          스팸 필터를 해제          ';
$stragismakoutivathos = '225';
$stepstragisedefaultlistkubi = '        기본 스팸 필터 목록 사용       ';
$stepstragisecustomlistkubi = '   사용자 지정 스팸 필터 목록 사용  ';
$stepstragisemessagepreshpeel = '스패머를 표시 하는 경고 메시지 사용자 지정:</span><div style="padding-top:8px;">당신은 그들이 귀하의 웹 사이트를 통해 의견을 게시 하 여 스팸 전송 하려고 하는 경우 스팸 메일에 표시 되는 메시지를 사용자 지정 하는 옵션.</div></div></td></tr><tr><td height="15px;"></td></tr><tr><td valign="top"><table cellpadding="0" cellspacing="0" border="0"><tr><td><div style="padding-left:15px;padding-right:15px;padding-top:10px;letter-spacing:1.2px;">&nbsp;현재 경고 메시지 스패머를 표시:';
$stepstragisemessagepostshpeel = '스패머에 대 한 새로운 경고 메시지 설정:</div></td></tr><tr><td align="left"style="padding:15px;padding-top:10px;"><span style="font-weight:bold;padding-left:5px;">메시지 제목: (굵게 표시 됩니다)</span><div style="padding-top:5px;padding-left:5px;"><input type="text" name="kakofanititlo" style="width:400px;font-weight:bold;" maxlength="100"></div></td></tr><tr><td align="left"style="padding:15px;padding-top:5px;"><span style="font-weight:bold;padding-left:5px;">메시지 내용';
$stepstragiseusedefaultkubi = '기본 스팸 메시지 사용';
$stepsave = '변경 내용을 저장합니다';
$stepsaveshpeel = '플러그인 설정을 변경한 경우 <span style="letter-spacing:1.2px;color:#000080;">변경 내용을 저장합니다</span> 단추를 클릭 하는 것을 기억 하시기 바랍니다.';
$stepsavesavekubi = '변경 내용을 저장합니다';
$stepsaverestoredefaultkubi = '기본 설정 복원';
$stepfeedback = '피드백';
$stepfeedbackpreshpeel = '귀하의 의견을 크게 주시면 감사 하겠습니다.<p>개선, 제안 등이 자료 WordPress 플러그인의 사용에 관한 어떤 생각을가지고 <span style="letter-spacing:1.2px;color:#000080;">피드백</span> 단추를 클릭 하십시오.</p>';
$stepfeedbackpostshpeel = '<strong>AlphaOmega Captcha & Anti-Spam Filter</strong>를 사용 하 여 주셔서 감사 합니다. ';

?>
