<?php

$stichiatitlo = 'AlphaOmega Captcha & Anti-Spam Filter Ρυθμίσεις';
$prindose = 'Το <span style="color:#000080;">AlphaOmega Captcha & Anti-Spam Filter</span> είναι ένα αποτελεσματικό και απλό στη χρήση captcha και ανεπιθύμητα μηνύματα spam plugin που να εμποδίζει την ανεπιθύμητη αλληλογραφία και φίλτρα καταχωρηθεί χρήστη σχόλια ακατάλληλου περιεχομένου. Αυτό το plugin μπορεί επίσης να ματαιώνουν αυτοματοποιημένη επιθέσεις εναντίον σας σελίδα αρχείου καταγραφής στο διοίκησης.<div style="padding-top:10px;">Οι προεπιλεγμένες ρυθμίσεις που φαίνεται παρακάτω παρέχουν υψηλό επίπεδο προστασίας κατά των αυτόκλητων μηνυμάτων και κακόβουλου admin καταγραφής στη σελίδα επιθέσεις. Έχετε επίσης την επιλογή, εάν θέλετε η συμπεριφορά πρόσθετες προσαρμοσμένες plugin προσαρμογή για τις προεπιλεγμένες ρυθμίσεις.';
$dosetitlo = 'Εξετάστε το ενδεχόμενο δωρίζετε';
$doseshpeel = 'Οι δημιουργοί του <span style="color:#000080;">AlphaOmega Captcha & Anti-Spam Filter</span> εκτιμούσα πολύ αν θα εξετάζατε το παρέχει μια μικρή δωρεά για να υποστηρίξουμε τη συνεχή ανάπτυξη δωρεάν αυτό το plugin, εάν το βρείτε χρήσιμο με οποιονδήποτε τρόπο. Κάθε ποσό το οποίο δωρεά θα εκτιμήσουν ταπεινά. Ευχαριστούμε.';
$doseinput = '<input type="hidden" name="country" value="GR" ><input type="hidden" name="item_name" value="Δωρεά για AlphaOmega Captcha & Anti-Spam Filter"><input type="hidden" name="currency_code" value="EUR">';
$dosekubitext = 'Παρακαλώ δωρεά';
$doseoutput = '<option value="5">&nbsp;€5 &nbsp; &nbsp;</option><option value="10">&nbsp;€10 &nbsp; &nbsp;</option><option value="15">&nbsp;€15 &nbsp;&nbsp;</option><option value="20">&nbsp;€20 &nbsp; &nbsp;</option><option value="25">&nbsp;€25 &nbsp; &nbsp;</option><option value="50">&nbsp;€50 &nbsp; &nbsp;</option>';
$dosepp = 'Δωρεές που υποβάλλονται σε επεξεργασία από το PayPal';
$stepglossa = 'Γλώσσα';
$stepglossaena = 'Αγγλικά';
$stepglossaenashpeel = 'Όλο το κείμενο αυτό πίνακα "Ρυθμίσεις" και το κείμενο που είναι παρακείμενα captcha εικόνες θα είναι στην αγγλική γλώσσα.';
$stepglossadio = 'Ιαπωνικά';
$stepglossadioshpeel = 'Όλο το κείμενο αυτό πίνακα "Ρυθμίσεις" και το κείμενο που είναι παρακείμενα captcha εικόνες θα στην ιαπωνική γλώσσα.';
$stepglossatria = 'Ελληνικά';
$stepglossatriashpeel = 'Όλο το κείμενο αυτό πίνακα "Ρυθμίσεις" και το κείμενο που είναι παρακείμενα captcha εικόνες θα είναι στην ελληνική γλώσσα.';
$stepglossatesera = 'Κορεατικά';
$stepglossateserashpeel = 'Όλο το κείμενο αυτό πίνακα "Ρυθμίσεις" και το κείμενο που είναι παρακείμενα captcha εικόνες θα στην κορεατική γλώσσα.';
$stepglossapente = 'Κινεζικά';
$stepglossapenteshpeel = 'Όλο το κείμενο αυτό πίνακα "Ρυθμίσεις" και το κείμενο που είναι παρακείμενα captcha εικόνες θα στην κινεζική γλώσσα.';
$stepcaptype = 'Τύπος captcha';
$stepcaptypeena = 'Απαιτεί από το χρήστη να εισαγάγει διάφορες αλφαβητικούς και αριθμητικούς χαρακτήρες.';
$stepcaptypedio = 'Απαιτεί από το χρήστη να εκτελέσετε μια απλή μαθηματική εργασία.';
$stepcaptypetria = 'Ο χρήστης πρέπει να εισαγάγει το όνομα του καλλιτέχνη.';
$stepcaptypetesera = 'Απαιτεί από το χρήστη να εισαγάγετε τον τίτλο της μια γνωστή ταινία.';
$stepcaptypepente = 'Ο χρήστης πρέπει να εισαγάγει το όνομα του συντάκτη.';
$stepcaptypeexi = 'Απαιτεί από το χρήστη να εισαγάγει μια απάντηση σε μια επιστημονική ερώτηση ή το κουίζ.';
$stepcaptypeefta = 'Απαιτεί από το χρήστη να εισαγάγει το όνομα του ένα περίφημο ιστορικό σχήμα.';
$stepcaptypeochto = 'Απαιτεί από το χρήστη να εισαγάγει τις λέξεις που αντιπροσωπεύεται από μια κοινή ακρωνύμιο.';
$stepcaptypeenea = 'Ο χρήστης πρέπει να εισαγάγετε το μουσικό όρο ή μέσο που εμφανίζονται.';
$stepcaptypedeca = 'Απαιτεί από το χρήστη να εισαγάγει το όνομα μιας πρωτεύουσα ή η γεωγραφική θέση.';
$stepcaptypeendeca = 'Ο χρήστης πρέπει να εισαγάγει την αριθμητική έννοια του το πρόθεμα της λέξης.';
$stepcaptypedodeca = 'Ο χρήστης πρέπει να εισαγάγετε το άθλημα που σχετίζεται με το άτομο που αναγράφεται.';
$stepcaptypedecatria = 'Απαιτεί από το χρήστη να εισαγάγετε το όνομα του διευθυντή ταινία που σκηνοθέτησε την ταινία που εμφανίζονται.';
$stepcaptypedecatesera = 'Απαιτεί από το χρήστη να εισαγάγετε το όνομα του όρου μόδα ή στοιχείο εμφανίζεται.';
$stepcaptypedecapente = 'Απαιτεί από το χρήστη να ονομάσετε τη χώρα που σχετίζεται με το νόμισμα που προκύπτει.';
$stepcaptypedecaexi = 'Απαιτεί από το χρήστη να ονομάσετε τη χώρα καταγωγής των τροφίμων στοιχείο εμφανίζεται.';
$stepcaptypedecaefta = 'Ο χρήστης καλείται να εισέλθουν στην ιατρική όνομα ή όρος που εμφανίζεται.';
$stepcaptypedecaochto = 'Ο χρήστης καλείται να εισέλθει ο όρος οικολογική φαίνεται.';
$stepcaptypedecaenea = 'Ο χρήστης καλείται να εισαγάγετε το όνομα του το γνωστό πρόγραμμα Τηλεόρασης.';
$stepcaptopos = 'Σελίδα captcha θέση';
$stepcaptoposcomm = 'Σχόλιο μορφή';
$stepcaptoposcommshpeel = 'Το captcha θα εμφανίζονται στη φόρμα σας σχόλιο. Το captcha πρέπει να συμπληρώνεται από ένα χρήστη που επιθυμεί να καταχωρήσετε ένα σχόλιο μετά την επίσκεψή του μία από τις καταχωρήσεις ιστολογίου σας.';
$stepcaptoposadmin = 'Σελίδα "Διαχείριση σύνδεσης"';
$stepcaptoposadminshpeel = 'Το captcha θα εμφανιστεί για σας admin καταγραφής στη σελίδα. Το captcha πρέπει να ολοκληρωθεί από ένα χρήστη που επιθυμεί να συνδεθείτε στο λογαριασμό σας Wordpress / ταμπλό.';
$stepcapepanomesikato = 'Captcha θέση';
$stepcapepanomesikatoshpeel = 'Η θέση του το captcha AlphaOmega μπορείτε να τοποθετήσετε σε το σχόλιο μορφή σας Wordpress θέσεις και τις σελίδες μπορεί να οριστεί σε κάθε μία από τρεις θέσεις: <span style="letter-spacing:1.2px;color:#000080;">Επάνω</span> ( T ), <span style="letter-spacing:1.2px;color:#000080;">Μέση</span> ( M ), ή <span style="letter-spacing:1.2px;color:#000080;">Κάτω</span> ( B ). Η θέση του το captcha AlphaOmega στη σελίδα "Διαχείριση σύνδεσης" στο είναι σταθερή θέση του κάτω ( B ).<div style="padding-top:10px;">Επιλέξτε τη θέση σας επιθυμητό captcha σχόλιο μορφή';
$stepcapepanomesikatotablecommtitle = 'Σχόλιο μορφή';
$stepcapepanomesikatotableadmintitle = 'Σελίδα "Διαχείριση σύνδεσης"';
$stepcapepanomesikatotablecommepano = 'T';
$stepcapepanomesikatotablecommmesi = 'M';
$stepcapepanomesikatotablecommkato = 'B';
$stepcapepanomesikatotablecommkubi = 'Αποστολή σχολίου';
$stepcapepanomesikatotableadminkato = 'B';
$stepcapepanomesikatotableadminkubi = 'Σύνδεση';
$stepstragise = 'Spam Φίλτρο';
$stepstragisepreshpeel = 'Το πρότυπο Wordpress σχόλιο μορφή περιέχει πολλά στοιχεία φόρμας, όπως όνομα, ηλεκτρονικού ταχυδρομείου, διεύθυνση URL, και σχόλιο ή μήνυμα.<p>Εάν οποιοδήποτε από αυτά τα στοιχεία φόρμας είναι παρόντες στη φόρμα σας σχόλιο, αυτή η ρύθμιση plugin σάς επιτρέπει να επιλέξετε τα στοιχεία των οποίων το περιεχόμενο που θέλετε να ελέγξετε ή να φιλτράρετε για δυνατόν spam. Σχόλιο παρατηρήσεις που περιέχουν λέξεις-κλειδιά που σχετίζονται με ανεπιθύμητη αλληλογραφία ή φράσεις (έχει ρυθμιστεί κάτω από με τις <span style="letter-spacing:1.2px;color:#000080;">Λίστα Φίλτρων Spam</span>) θα αποκλειστεί, και δεν αποστέλλονται σε εσάς.</p><p>Αυτό μπορεί να είναι ένα πολύ αποτελεσματικό τρόπο να ματαιώνουν αδυσώπητο αυτόματου και μη αυτόματου spam επιθέσεις, και ως εκ τούτου, δωρεάν περιοχή σας Wordpress Admin, από την πληθώρα ανεπιθύμητα και ενοχλητικά ηλεκτρονικά μηνύματα spam που σχετίζονται με σχόλια.</p>';
$stepstragisetitlo = 'Επιλέξτε τα στοιχεία φόρμας σχόλιο για φιλτράρισμα ανεπιθύμητης ηλεκτρονικής αλληλογραφίας';
$stepstragiseonoma = 'Όνομα';
$stepstragisediefthinsi = 'Ηλεκτρονικό ταχυδρομείο';
$stepstragisehitaftafpi = 'URL';
$stepstragiseminima = 'Σχόλια / μήνυμα';
$stepstragisepostshpeel = 'Ρύθμιση παραμέτρων της λίστας φίλτρων Spam:</span><div style="padding-top:8px;">Μπορείτε να χρησιμοποιήσετε το <span style="letter-spacing:1.2px;color:#000080;">Λίστα Φίλτρων Spam Προεπιλογή</span> ή να κάνουν τη δική σας <span style="letter-spacing:1.2px;color:#000080;">Προσαρμοσμένη Λίστα Φίλτρων Spam</span> να ελέγξετε σχόλιο παρατηρήσεις για το περιεχόμενο που σχετίζονται με την ανεπιθύμητη αλληλογραφία.<p>Για να δημιουργήσετε τις δικές σας <span style="letter-spacing:1.2px;color:#000080;">Προσαρμοσμένη Λίστα Φίλτρων Spam</span>, κάντε κλικ στο κουμπί <span style="letter-spacing:1.2px;color:#000080;">Απενεργοποίηση Φίλτρο Ανεπιθύμητης Αλληλογραφίας</span> και, στη συνέχεια, πληκτρολογήστε σας λέξεις-κλειδιά που σχετίζονται με ανεπιθύμητη αλληλογραφία ή/και φράσεις στο πλαίσιο λίστας-παρακάτω. Κάθε λέξη-κλειδί ή φράση πρέπει να είναι σε ξεχωριστή γραμμή.</p><p>Το <strong>Spam Φίλτρο</strong> αυτόματα αναλαμβάνει όλες τις παραλλαγές πεζά και τα κεφαλαία του σήμερα στη λίστα λέξεις-κλειδιά/φράσεις. Ως εκ τούτου, η προσθήκη <span style="letter-spacing:1.2px;color:#000080;">Yellow Hat</span> και <span style="letter-spacing:1.2px;color:#000080;">yellow hat</span> σε δύο ξεχωριστές γραμμές είναι περιττή. Χρειάζεστε μόνο για να προσθέσετε, για παράδειγμα, <span style="letter-spacing:1.2px;color:#000080;">yellow hat</span> σε μία μόνο γραμμή.</p><p>Τέλος, αποφύγετε τη χρήση των πληθυντικός μορφών λέξεις-κλειδιά/φράσεις---Χρησιμοποιήστε το <span style="letter-spacing:1.2px;color:#000080;">yellow hat</span> αντί για <span style="letter-spacing:1.2px;color:#000080;">yellow hats</span>.</p><p>Μία φορά έχετε κάνει το <span style="letter-spacing:1.2px;color:#000080;">Προσαρμοσμένη Λίστα Φίλτρων Spam</span> σας, κάντε κλικ στο κουμπί <span style="letter-spacing:1.2px;color:#000080;">Αποθηκεύστε τις αλλαγές</span> (βήμα 6) για να αποθηκεύσετε σας προσαρμοσμένη λίστα. Λέξεις-κλειδιά/φράσεις μπορεί να προσαρτηθεί ή να διαγραφεί από το <span style="letter-spacing:1.2px;color:#000080;">Προσαρμοσμένη Λίστα Φίλτρων Spam</span> σας οποιαδήποτε στιγμή, και σας τροποποιημένο κατάλογο μπορεί στη συνέχεια να αποθηκευτεί, κάνοντας κλικ στο κουμπί <span style="letter-spacing:1.2px;color:#000080;">Αποθηκεύστε τις αλλαγές</span> (βήμα 6).</p><div style="color:#a80000;padding-top:7px;padding-bottom:10px;">Εάν δεν θέλετε να φιλτράρετε τα σχόλιά σας για ανεπιθύμητη αλληλογραφία, απλά καταργήστε την επιλογή όλων των στοιχείων σχόλιο μορφή που εμφανίζεται παραπάνω ή κάντε κλικ στο κουμπί <span style="letter-spacing:1.2px;color:#000080;">Απενεργοποίηση Φίλτρο Ανεπιθύμητης Αλληλογραφίας</span>.';
$stepstragiseremovelistkubi = '                 Απενεργοποίηση Φίλτρο Ανεπιθύμητης Αλληλογραφίας                  ';
$stragismakoutivathos = '575';
$stepstragisedefaultlistkubi = 'Χρησιμοποιήστε τη λίστα προεπιλεγμένο φίλτρο ανεπιθύμητης αλληλογραφίας';
$stepstragisecustomlistkubi = '                          Χρησιμοποιήστε τη λίστα φίλτρων Spam Custom                          ';
$stepstragisemessagepreshpeel = 'Προσαρμόστε το προειδοποιητικό μήνυμα εμφανίζεται σε αποστολείς ανεπιθύμητης αλληλογραφίας:</span><div style="padding-top:8px;">Έχετε την επιλογή Προσαρμογή της το μήνυμα που εμφανίζεται σε κάποιον αποστολέα ανεπιθύμητης αλληλογραφίας, αν προσπαθούν να σας στείλουμε ανεπιθύμητα μηνύματα από καταχώρησης ένα σχόλιο μέσω της τοποθεσίας σας στο web.</div></div></td></tr><tr><td height="15px;"></td></tr><tr><td valign="top">
<table cellpadding="0" cellspacing="0" border="0"><tr><td><div style="padding-left:15px;padding-right:15px;padding-top:10px;letter-spacing:1.2px;">
&nbsp;Τρέχον μήνυμα προειδοποίησης που εμφανίζεται σε αποστολείς ανεπιθύμητης αλληλογραφίας:';
$stepstragisemessagepostshpeel = 'Ορίστε ένα νέο μήνυμα προειδοποίησης για αποστολείς ανεπιθύμητης αλληλογραφίας:</div></td></tr><tr><td align="left"style="padding:15px;padding-top:10px;"><span style="font-weight:bold;padding-left:5px;">Τίτλος μηνύματος: (θα εμφανίζεται με έντονη γραφή)</span><div style="padding-top:5px;padding-left:5px;"><input type="text" name="kakofanititlo" style="width:400px;font-weight:bold;" maxlength="100">
</div></td></tr><tr><td align="left"style="padding:15px;padding-top:5px;"><span style="font-weight:bold;padding-left:5px;">Περιεχόμενο μηνύματος';
$stepstragiseusedefaultkubi = 'Χρησιμοποιήστε το προεπιλεγμένο μήνυμα που Spam';
$stepsave = 'Αποθηκεύστε τις αλλαγές';
$stepsaveshpeel = 'Σας παρακαλούμε να θυμηθείτε να κάνετε κλικ στο κουμπί <span style="letter-spacing:1.2px;color:#000080;">Αποθηκεύστε τις αλλαγές</span>, εάν έχετε αλλάξει τις ρυθμίσεις του plugin σας.';
$stepsavesavekubi = 'Αποθηκεύστε τις αλλαγές';
$stepsaverestoredefaultkubi = 'Επαναφέρετε τις προεπιλεγμένες ρυθμίσεις';
$stepfeedback = 'Σχόλια';
$stepfeedbackpreshpeel = 'Τα σχόλιά σας θα εκτιμούσαμε.<p>Εάν έχετε κάποιες σκέψεις σχετικά με τη χρήση των το WordPress plugin, συμπεριλαμβανομένων προτάσεων για βελτιώσεις, κάντε κλικ στο κουμπί <span style="letter-spacing:1.2px;color:#000080;">Σχόλια</span>.</p>';
$stepfeedbackpostshpeel = 'Ευχαριστούμε που χρησιμοποιείτε το <strong>AlphaOmega Captcha & Anti-Spam Filter</strong>.';

?>
