<?php

// Generated by './vendor/bin/php-generate-autoload' 'src/autoload.php'

\spl_autoload_register(function ($class) {
  static $map = array (
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Acl' => 'Acl.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Configuration' => 'Configuration.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Connector' => 'Connector.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\CannotDeleteFile' => 'Exception/CannotDeleteFile.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\CannotGetBucket' => 'Exception/CannotGetBucket.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\CannotGetFile' => 'Exception/CannotGetFile.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\CannotListBuckets' => 'Exception/CannotListBuckets.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\CannotOpenFileForRead' => 'Exception/CannotOpenFileForRead.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\CannotOpenFileForWrite' => 'Exception/CannotOpenFileForWrite.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\CannotPutFile' => 'Exception/CannotPutFile.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\ConfigurationError' => 'Exception/ConfigurationError.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\InvalidAccessKey' => 'Exception/InvalidAccessKey.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\InvalidBody' => 'Exception/InvalidBody.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\InvalidEndpoint' => 'Exception/InvalidEndpoint.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\InvalidFilePointer' => 'Exception/InvalidFilePointer.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\InvalidRegion' => 'Exception/InvalidRegion.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\InvalidSecretKey' => 'Exception/InvalidSecretKey.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\InvalidSignatureMethod' => 'Exception/InvalidSignatureMethod.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Exception\\PropertyNotFound' => 'Exception/PropertyNotFound.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Input' => 'Input.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Request' => 'Request.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Response' => 'Response.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Response\\Error' => 'Response/Error.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Signature' => 'Signature.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Signature\\V2' => 'Signature/V2.php',
  'Akeeba\\Engine\\Postproc\\Connector\\S3v4\\Signature\\V4' => 'Signature/V4.php',
);

  if (isset($map[$class])) {
    require_once __DIR__ . '/' . $map[$class];
  }
}, true, false);


