<?php ob_start(); ?>
<style type="text/css">
    .subsubsub li+li:before {content:'| ';}
</style>
<span id="cmgdm_admin_nav">
<ul class="subsubsub">
    <?php foreach ($submenus as $menu): ?>
    <li><a href="<?php echo $menu['link']; ?>" <?php echo ($menu['current'])?'class="current"':''; ?>><?php echo $menu['title']; ?></a></li>
    <?php endforeach; ?>
</ul>
<br class="clear" />
</span>
<?php ob_end_flush();