
<div class="cmbl-get-pro">
	<p><strong>Get the professional version of CM Email Blacklist which gives you:</strong></p>
	<ul class="cmbl-pro-features">
		<li>DNSLB online service fdomain iltering</li>
		<li>User Blacklist</li>
		<li>Log Registration Attempts</li>
		<li>Accept only whitelisted domains</li>
		<li>...and much more!</li>
	</ul>

        <p class="center"><a href="https://www.cminds.com/wordpress-plugins-library/email-registration-blacklist-plugin-for-wordpress/" class="button">Upgrade to Pro</a></p>
</div>