<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'blobfolio\\wp\\meow\\about' => '/blobfolio/wp/meow/about.php',
                'blobfolio\\wp\\meow\\admin' => '/blobfolio/wp/meow/admin.php',
                'blobfolio\\wp\\meow\\ajax' => '/blobfolio/wp/meow/ajax.php',
                'blobfolio\\wp\\meow\\cli' => '/blobfolio/wp/meow/cli.php',
                'blobfolio\\wp\\meow\\cli\\activity' => '/blobfolio/wp/meow/cli/activity.php',
                'blobfolio\\wp\\meow\\cli\\jail' => '/blobfolio/wp/meow/cli/jail.php',
                'blobfolio\\wp\\meow\\cli\\security' => '/blobfolio/wp/meow/cli/security.php',
                'blobfolio\\wp\\meow\\cli\\settings' => '/blobfolio/wp/meow/cli/settings.php',
                'blobfolio\\wp\\meow\\core' => '/blobfolio/wp/meow/core.php',
                'blobfolio\\wp\\meow\\db' => '/blobfolio/wp/meow/db.php',
                'blobfolio\\wp\\meow\\hooks' => '/blobfolio/wp/meow/hooks.php',
                'blobfolio\\wp\\meow\\login' => '/blobfolio/wp/meow/login.php',
                'blobfolio\\wp\\meow\\options' => '/blobfolio/wp/meow/options.php',
                'blobfolio\\wp\\meow\\tools' => '/blobfolio/wp/meow/tools.php',
                'blobfolio\\wp\\meow\\vendor\\common\\bc' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/bc.php',
                'blobfolio\\wp\\meow\\vendor\\common\\cast' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/cast.php',
                'blobfolio\\wp\\meow\\vendor\\common\\cli' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/cli.php',
                'blobfolio\\wp\\meow\\vendor\\common\\constants' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/constants.php',
                'blobfolio\\wp\\meow\\vendor\\common\\data' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/data.php',
                'blobfolio\\wp\\meow\\vendor\\common\\dom' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/dom.php',
                'blobfolio\\wp\\meow\\vendor\\common\\file' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/file.php',
                'blobfolio\\wp\\meow\\vendor\\common\\format' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/format.php',
                'blobfolio\\wp\\meow\\vendor\\common\\mb' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/mb.php',
                'blobfolio\\wp\\meow\\vendor\\common\\ref\\cast' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/cast.php',
                'blobfolio\\wp\\meow\\vendor\\common\\ref\\file' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/file.php',
                'blobfolio\\wp\\meow\\vendor\\common\\ref\\format' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/format.php',
                'blobfolio\\wp\\meow\\vendor\\common\\ref\\mb' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/mb.php',
                'blobfolio\\wp\\meow\\vendor\\common\\ref\\sanitize' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/sanitize.php',
                'blobfolio\\wp\\meow\\vendor\\common\\sanitize' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/sanitize.php',
                'blobfolio\\wp\\meow\\vendor\\domain\\data' => '/vendor/blobfolio/blob-domain/lib/blobfolio/domain/data.php',
                'blobfolio\\wp\\meow\\vendor\\domain\\domain' => '/vendor/blobfolio/blob-domain/lib/blobfolio/domain/domain.php',
                'blobfolio\\wp\\meow\\vendor\\md\\parsedown' => '/vendor/erusev/parsedown/Parsedown.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
