export const CORE_NOTICE = 'core/notices';
export const ID_NOTICE = {
  ACFWF_NOTICE_BOGO: 'ACFWF_NOTICE_BOGO',
  ACFWF_NOTICE_CART_CONDITIONS: 'ACFWF_NOTICE_CART_CONDITIONS',
  ACFWF_NOTICE_STORE_CREDIT: 'ACFWF_NOTICE_STORE_CREDIT',
};
