<style type="text/css">
	
	#wpsgitrecht_message { margin-left:5px; }
	.wpsgitrecht_clear { clear:both; }
	.wpsgitrecht_form_field { width:770px; margin-bottom:5px; }
	.wpsgitrecht_form_field .wpsgitrecht_form_left { line-height:24px; font-weight:bold; width:350px; float:left; }
	.wpsgitrecht_form_field .wpsgitrecht_form_right { width:420px; float:left; position:relative; line-height:28px; }
	.wpsgitrecht_form_field .wpsgitrecht_form_right select, .wpsgitrecht_form_field .wpsgitrecht_form_right input { width:95%; }
	.wpsgitrecht_form_field .wpsgitrecht_form_right input.checkbox { width:auto !important; float:left; margin-left:2px; margin-top:5px; }
	.wpsgitrecht_form_field .wpsgitrecht_form_right p { padding:4px 0px 4px 6px; margin:0px; }
	.wpsgitrecht_form { padding:10px; }
	.wpsgitrecht_date { float:right; padding-right:5%; }
	.wpsgitrecht_hinweis { font-style:italic; }
	.wpsgitrecht_table { border-spacing:0px; border-collapse:collapse; }
	.wpsgitrecht_table .col0 { width:347px; }
	.wpsgitrecht_table .col1 { width:400px; }
	.wpsgitrecht_table .col1 p { padding:2px 0px 2px 10px; display:inline-block; margin:0px; }
	.wpsgitrecht_table .col1 select { width:100%; }
	.wpsgitrecht_table .col4 label { margin-right:15px; }
	.wpsg_itrecht_generatebutton { width:16px; height:16px; background-image:url('<?php echo site_url(); ?>/wp-content/plugins/wpshopgermany-itrecht/views/gfx/arrow_refresh_small.png'); ?>); display:inline-block; float:right; margin-top:6px; }
	
</style>

<?php echo $this->writeBackendMessage(); ?>
	
<div class="wrap">
	<div id="icon-options-general" class="icon32">
		<br>
	</div>
	<h2><?php echo __('WpShopGermany - IT-Recht Kanzlei München', 'wpsgitrecht'); ?></h2>

	<form method="POST" class="wpsgitrecht_form">
		
		<?php echo $this->showForm(); ?>
		
		<div class="wpsgitrecht_clear"></div>
		<br />
		<input type="submit" value="<?php echo __('Speichern', 'wpsgitrecht'); ?>" name="wpsgitrecht_submit" class="button-primary" />
	
	</form>
	
</div>