<?php echo $this->render('template-page.phtml'); ?>
<hr>
<section class="header">
    <img class="options" src="<?php echo plugins_url('/img/logo.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="Logo">
</section>
<div id="main-content">
    <section class="universal-plugin-header">
        <div class="background">
            <div class="container">
                <div class="item">
                    <h1>Cart2Cart<br> <span class="bolder-text">Universal Migration app</span></h1>
                    <p>
                        Perform an automated store data transfer without having to dive into codes and scripts.
                        The entire process can be done through your WordPress interface with no redirections at all.
                    </p>
                </div>
                <div class="item">
                    <img class="img" src="<?php echo plugins_url('/img/universal-app.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="Universal Migration">
                </div>
            </div>
        </div>
    </section>
    <section class="four-items-block">
        <div class="container">
            <h2 class="like-heading-h2">How to <span class="bolder-text">Migrate to WooCommerce In 4 Steps?</span></h2>
            <div class="items-list universal-plugin-steps">
                <div class="item">
                    <div class="icon-circle">01</div>
                    <h3 class="like-heading-h3">Connect the Source &<br> Target carts</h3>
                </div>
                <div class="item">
                    <div class="icon-circle">02</div>
                    <h3 class="like-heading-h3">Choose the entities &<br> extra options</h3>
                </div>
                <div class="item">
                    <div class="icon-circle">03</div>
                    <h3 class="like-heading-h3">Run Demo migration</h3>
                </div>
                <div class="item">
                    <div class="icon-circle">04</div>
                    <h3 class="like-heading-h3">Launch Full migration</h3>
                </div>
            </div>
        </div>
    </section>
    <section class="universal-plugin-block">
        <div class="container">
            <div class="like-heading-h2">Why Choose <span class="bolder-text">Cart2Cart Universal Migration App?</span></div>
            <div class="block">
                <div class="item">
                    <p>
                        Performing eCommerce migration via the Cart2Cart Universal Migration app doesn’t require a
                        lot of time and effort, offering many benefits instead:
                    </p>
                    <ul>
                        <li>High speed of data transfer</li>
                        <li>Finest migration quality</li>
                        <li>No special skills expected</li>
                        <li>The widest range of supported entities</li>
                        <li>Pricing estimator available</li>
                        <li>Migration Preview with no Target cart required</li>
                        <li>Free Demo</li>
                    </ul>
                    <p>
                        Unfortunately, the <strong>design and 3rd-party apps migration is impossible</strong> due to
                        technical peculiarities
                    </p>
                </div>
                <div class="item">
                    <img class="img" src="<?php echo plugins_url('/img/universal-migration.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="Universal Migration">
                </div>
                <div class="item">
                    <a class="main-green-button" href="https://app.shopping-cart-migration.com/" data-toggle="modal" target="_blank">
                        Start migration
                        <div class="button-img">
                            <img src="<?php echo plugins_url('/img/click.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="click">
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <section class="universal-plugin-block blue">
        <div class="container">
            <div class="like-heading-h2">What Data Can Be <span class="bolder-text">Migrated via the Cart2Cart Universal Migration App?</span></div>
            <div class="block">
                <div class="item">
                    <p>
                        Cart2Cart has all the necessary functionality to migrate every possible eСommerce data type
                        (Products, Customers, Orders, Reviews, Blog Posts, Categories, etc.) and its accompanying
                        attributes.
                    </p>
                    <p>
                        <strong>
                            However, since the transferrable data change depending on your current store, we
                            recommend checking the exact list of transferrable entities at the Cart2Cart official
                            website
                        </strong>
                    </p>
                </div>
                <div class="item">
                    <img class="img" src="<?php echo plugins_url('/img/data-migration.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="Data Migration">
                </div>
                <div class="item">
                    <a class="main-green-button" href="https://www.shopping-cart-migration.com/supported-carts/4418-woocommerce" data-toggle="modal" target="_blank">
                        Check Details
                        <div class="button-img">
                            <img src="<?php echo plugins_url('/img/click.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="click">
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <section class="universal-plugin-block">
        <div class="container">
            <div class="like-heading-h2">How Much Does It Cost to <span class="bolder-text">Migrate to WooCommerce via the Cart2Cart App?</span></div>
            <div class="block">
                <div class="item">
                    <p>
                        The starting migration price is $29. The final cost of the migration depends on the number
                        of store entities that need to be transferred and the additional migration options.
                    </p>
                    <p>
                        <strong>You can use the</strong>
                        <a class="link" target="_blank" href="https://www.shopping-cart-migration.com/migration-pricing">Cart2Cart Migration Estimator</a>
                        to calculate the exact cost of your specific migration case.
                    </p>
                    <p>
                        For custom migration needs, there are <a class="link" target="_blank" href="https://www.shopping-cart-migration.com/provided-services/data-migration-service-packages">all-in-one service packages</a> available to outsource
                        the data migration task to Cart2Cart technical engineers.
                    </p>
                    <div class="warning-note">
                        <img src="<?php echo plugins_url('/img/warning.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="Warning">
                        <p>Note that with Cart2Cart, you won’t be charged until you’re happy with the Demo migration outcome.</p>
                    </div>
                </div>
                <div class="item">
                    <img class="img" src="<?php echo plugins_url('/img/cost-migration.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="Cost Migration">
                </div>
                <div class="item">
                    <a class="main-green-button" href="https://app.shopping-cart-migration.com/" data-toggle="modal" target="_blank">
                        Start migration
                        <div class="button-img">
                            <img src="<?php echo plugins_url('/img/click.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="click">
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
</div>
<section class="footer">
    <img class="options" src="<?php echo plugins_url('/img/logo.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="Logo">
</section>
<style>
    .universal-plugin-block .item ul li:before {
        content: url(<?php echo plugins_url('/img/check.svg', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>);
        height: 12px;
        width: 16px;
        margin-right: 20px;
    }
</style>