var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,g=0;g<d;g++){var l=a[g];if(b.call(c,l,g,a))return{i:g,v:l}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var g=a[d];g in c||(c[g]={});c=c[g]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,a){return $jscomp.findInternal(this,b,a).v}},"es6","es3");
function generate_the_eddmp(a){if(!("boolean"!==typeof a&&"undefined"!=typeof eddmp_global_settings&&1*eddmp_global_settings.onload)&&"undefined"===typeof generated_the_eddmp){generated_the_eddmp=!0;var b=jQuery;b(".eddmp-player-container").on("click","*",function(e){e.preventDefault();e.stopPropagation();return!1});b.expr.pseudos.regex=function(e,a,c){a=c[3].split(",");var d=/^(data|css):/;c=a[0].match(d)?a[0].split(":")[0]:"attr";d=a.shift().replace(d,"");return(new RegExp(a.join("").replace(/^\s+|\s+$/g,
""),"ig")).test(b(e)[c](d))};var c=[],d=0,g="undefined"!=typeof eddmp_global_settings?eddmp_global_settings.play_all:!0,l="undefined"!=typeof eddmp_global_settings?1*eddmp_global_settings.fade_out:!0;a="undefined"!=typeof eddmp_global_settings?!(1*eddmp_global_settings.play_simultaneously):!0;var m="undefined"!=typeof eddmp_global_settings&&"ios_controls"in eddmp_global_settings&&1*eddmp_global_settings.ios_controls?!0:!1,n=b("audio.eddmp-player:not(.track):not([playerNumber])"),p=b("audio.eddmp-player.track:not([playerNumber])"),
k={pauseOtherPlayers:a,iPadUseNativeControls:m,iPhoneUseNativeControls:m,success:function(a,f){var e=b(f).data("duration"),k=b(f).data("estimated_duration"),m=b(f).attr("playerNumber");"undefined"!=typeof k&&(a.getDuration=function(){return k});"undefined"!=typeof e&&setTimeout(function(a,d){return function(){c[a].updateDuration=function(){b(this.media).closest(".eddmp-player").find(".mejs-duration").html(d)};c[a].updateDuration()}}(m,e),50);b(f).attr("volume")&&(a.setVolume(parseFloat(b(f).attr("volume"))),
0==a.volume&&a.setMuted(!0));a.addEventListener("timeupdate",function(c){c=a.getDuration();isNaN(a.currentTime)||isNaN(c)||(l&&4>c-a.currentTime?a.setVolume(a.volume-a.volume/3):("undefined"==typeof a.bkVolume&&(a.bkVolume=parseFloat(b(a).find("audio,video").attr("volume")||a.volume)),a.setVolume(a.bkVolume),0==a.bkVolume&&a.setMuted(!0)))});a.addEventListener("volumechange",function(b){b=a.getDuration();isNaN(a.currentTime)||isNaN(b)||!(4<b-a.currentTime)&&l||!a.currentTime||(a.bkVolume=a.volume)});
a.addEventListener("ended",function(e){var f=b(a).closest('[data-loop="1"]');a.currentTime=0;if(1*g||f.length)if(e=1*b(a).attr("playerNumber"),isNaN(e)&&(e=1*b(a).find("[playerNumber]").attr("playerNumber")),f=f.length,e+1<d||f){var h=e+1;!f||h!=d&&0!=b('[playerNumber="'+h+'"]').closest("[data-loop]").length&&b('[playerNumber="'+h+'"]').closest("[data-loop]")[0]==b('[playerNumber="'+e+'"]').closest("[data-loop]")[0]||(h=b('[playerNumber="'+e+'"]').closest("[data-loop]").find("[playerNumber]:first").attr("playerNumber"));
c[h]instanceof b&&c[h].is("a")?c[h].trigger("click"):c[h].play()}})}};n.each(function(){var a=b(this);a.find("source").attr("src");a.attr("playerNumber",d);k.audioVolume="vertical";try{c[d]=new MediaElementPlayer(a[0],k)}catch(f){"console"in window&&console.log(f)}d++});p.each(function(){var a=b(this);a.find("source").attr("src");a.attr("playerNumber",d);k.features=["playpause"];try{c[d]=new MediaElementPlayer(a[0],k)}catch(f){"console"in window&&console.log(f)}d++})}}
function eddmp_force_init(){delete window.generated_the_eddmp;generate_the_eddmp(!0)}jQuery(generate_the_eddmp);
jQuery(window).on("load",function(){generate_the_eddmp(!0);var a=jQuery,b=window.navigator.userAgent;a("[data-lazyloading]").each(function(){var b=a(this);b.attr("preload",b.data("lazyloading"))});if(b.match(/iPad/i)||b.match(/iPhone/i))if("undefined"!=typeof eddmp_global_settings?eddmp_global_settings.play_all:1)a(".eddmp-player .mejs-play button").one("click",function(){if("undefined"==typeof eddmp_preprocessed_players){eddmp_preprocessed_players=!0;var b=a(this);a(".eddmp-player audio").each(function(){this.play();
this.pause()});setTimeout(function(){b.trigger("click")},500)}})}).on("popstate",function(){jQuery("audio[data-download]:not([playerNumber])").length&&eddmp_force_init()});jQuery(document).on("scroll",eddmp_force_init);
