<?php echo $this->render('template-page.phtml'); ?>
<hr>
<section class="header">
    <img class="options" src="<?php echo plugins_url('/img/logo.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="Logo">
</section>
<div id="main-content">
    <section class="universal-plugin-header">
        <div class="background">
            <div class="container">
                <div class="item">
                    <h1><span class="bolder-text">Additional</span> Options</h1>
                </div>
                <div class="item">
                    <img class="options" src="<?php echo plugins_url('/img/additional-options.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="Additional Options">
                </div>
            </div>
        </div>
    </section>
    <section class="universal-plugin">
        <div class="container">
            <div class="items-list">
                <div class="item service-packages">
                    <div class="icon-circle">
                        <div class="icon"></div>
                    </div>
                    <p class="heading">Data Migration Service Packages</p>
                    <p>
                        Users having no time or resources to handle the store migration can delegate the job to the
                        Cart2Cart migration experts and get the job done. We offer various Data Migration Service
                        Packages that include different volumes of transferable data and scope of customizations.
                    </p>
                    <a href="https://www.shopping-cart-migration.com/provided-services/data-migration-service-packages" class="main-white-button" target="_blank">
                        Learn more
                        <div class="button-img">
                            <img src="<?php echo plugins_url('/img/eyes.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                            <img src="<?php echo plugins_url('/img/eyes-white.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                        </div>
                    </a>
                </div>
                <div class="item recent">
                    <div class="icon-circle">
                        <div class="icon"></div>
                    </div>
                    <p class="heading">Recent Data Migration Service</p>
                    <p>
                        New data entities have appeared on your Source store during or after the Full migration?
                        With Cart2Cart’s Recent Data Migration Service, you can move all the newly added products,
                        customers, and orders to the Target platform without affecting the rest of the database.
                    </p>
                    <a href="https://www.shopping-cart-migration.com/provided-services/recent-data-migration-service" class="main-white-button" target="_blank">
                        Learn more
                        <div class="button-img">
                            <img src="<?php echo plugins_url('/img/eyes.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                            <img src="<?php echo plugins_url('/img/eyes-white.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                        </div>
                    </a>
                </div>
                <div class="item insurance">
                    <div class="icon-circle">
                        <div class="icon"></div>
                    </div>
                    <p class="heading">Migration Insurance Service</p>
                    <p>
                        Migration Insurance Service has been developed to protect you from unforeseen difficulties
                        by giving you the chance to restart the migration process. Simply choose one of the Insurance
                        plans on migration Wizard and get rid of all the fears, tension, and anxiety.
                    </p>
                    <a href="https://www.shopping-cart-migration.com/provided-services/migration-insurance-service" class="main-white-button" target="_blank">
                        Learn more
                        <div class="button-img">
                            <img src="<?php echo plugins_url('/img/eyes.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                            <img src="<?php echo plugins_url('/img/eyes-white.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                        </div>
                    </a>
                </div>
            </div>
            <div class="items-list">
                <div class="item preview">
                    <div class="icon-circle">
                        <div class="icon"></div>
                    </div>
                    <p class="heading">Migration Preview Service</p>
                    <p>
                        Still unsure about which eCommerce platform to choose for your store? With the Migration
                        Preview service, you can see how your own store data will appear on the top eCommerce
                        platforms without even having to install them. No cost, complete admin access to the test
                        store and make your decision.
                    </p>
                    <a href="https://www.shopping-cart-migration.com/provided-services/migration-preview-service" class="main-white-button" target="_blank">
                        Learn more
                        <div class="button-img">
                            <img src="<?php echo plugins_url('/img/eyes.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                            <img src="<?php echo plugins_url('/img/eyes-white.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                        </div>
                    </a>
                </div>
                <div class="item csv">
                    <div class="icon-circle">
                        <div class="icon"></div>
                    </div>
                    <p class="heading">CSV. File Data Migration</p>
                    <p>
                        In case your shopping cart isn’t supported by Cart2Cart, you can use the CSV.File
                        migration for eCommerce data import or export. Cart2Cart can perform the data transfer
                        either automatedly or via Data Service Packages with the required customizations.
                    </p>
                    <a href="https://www.shopping-cart-migration.com/provided-services/csv-migration" class="main-white-button" target="_blank">
                        Learn more
                        <div class="button-img">
                            <img src="<?php echo plugins_url('/img/eyes.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                            <img src="<?php echo plugins_url('/img/eyes-white.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                        </div>
                    </a>
                </div>
                <div class="item dump">
                    <div class="icon-circle">
                        <div class="icon"></div>
                    </div>
                    <p class="heading">Database Dump Migration</p>
                    <p>
                        In case your current website is collapsed or you have any security issues, Cart2Cart
                        database dump migration is an optimal go-out. It allows moving your data from a SQL
                        database dump into the new shopping cart within a Data Migration package.
                    </p>
                    <a href="https://www.shopping-cart-migration.com/provided-services/database-dump-migration-service" class="main-white-button" target="_blank">
                        Learn more
                        <div class="button-img">
                            <img src="<?php echo plugins_url('/img/eyes.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                            <img src="<?php echo plugins_url('/img/eyes-white.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
</div>
<section class="footer">
    <img class="options" src="<?php echo plugins_url('/img/logo.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="Logo">
</section>
<style>
    .universal-plugin .icon-circle .icon {
        width: 32px;
        height: 32px;
        background: url(<?php echo plugins_url('/img/sprites.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>) -63px -10px no-repeat;
    }
    .universal-plugin-header .background {
        width: 100%;
        background-image: url(<?php echo plugins_url('/img/background.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>);
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat,repeat;
    }

</style>