<?php echo $this->render('template-page.phtml'); ?>
<hr>
<section class="header">
    <img class="options" src="<?php echo plugins_url('/img/logo.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="Logo">
</section>
<div id="main-content">
    <section class="three-items-block">
        <div class="background">
            <div class="container">
                <h2><span class="bolder-text">Help</span> Section</h2>
                <p>Still need help? Do not hesitate to contact us via any of the options below.</p>
                <div class="items-list">
                    <div class="item just-copy">
                        <div class="icon-circle faq">
                            <div class="icon"></div>
                        </div>
                        <p class="heading">FAQ Directory</p>
                        <p>Visit our extensive FAQ directory for more info</p>
                        <a href="https://www.shopping-cart-migration.com/faq" class="main-white-button" target="_blank">
                            read more
                            <div class="button-img">
                                <img src="<?php echo plugins_url('/img/eyes.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                                <img src="<?php echo plugins_url('/img/eyes-white.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                            </div>
                        </a>
                    </div>
                    <div class="item">
                        <div class="icon-circle call">
                            <div class="icon"></div>
                        </div>
                        <p class="heading">Schedule a call</p>
                        <p>Book a call with Cart2Cart migration expert</p>
                        <a href="https://meetings.hubspot.com/c2c/cart2cart-personal-consultation" class="main-white-button" target="_blank">
                            read more
                            <div class="button-img">
                                <img src="<?php echo plugins_url('/img/eyes.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                                <img src="<?php echo plugins_url('/img/eyes-white.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                            </div>
                        </a>
                    </div>
                    <div class="item paste-code">
                        <div class="icon-circle submit-request">
                            <div class="icon"></div>
                        </div>
                        <p class="heading">Submit request</p>
                        <p>Request help by submitting a support ticket</p>
                        <a href="https://support.magneticone.com/hc/en-us/requests/new" class="main-white-button" target="_blank">
                            read more
                            <div class="button-img">
                                <img src="<?php echo plugins_url('/img/eyes.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                                <img src="<?php echo plugins_url('/img/eyes-white.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="eyes">
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<section class="footer">
    <img class="options" src="<?php echo plugins_url('/img/logo.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>" alt="Logo">
</section>
<style>
    .icon-circle .icon {
        width: 26px;
        height: 24px;
        background: url(<?php echo plugins_url('/img/help-section.png', CART2CART_PLUGIN_ROOT_DIR . 'dir'); ?>) -55px -10px no-repeat #00AEEF;
    }
</style>